/**
 * Cheatsheet — structured reference of the commands supported by the
 * in-browser sandbox in `src/lib/shell/evaluator.ts`. The cheatsheet
 * page filters this list client-side.
 *
 * Keep this file dependency-free so it can be imported from server or
 * client components.
 */

export type CheatCategory =
  | 'Navigation'
  | 'Files'
  | 'Inspection'
  | 'Editing'
  | 'Permissions'
  | 'Text'
  | 'Search'
  | 'Network'
  | 'Archiving'
  | 'System'
  | 'Help';

export interface CheatEntry {
  /** Command name, e.g. "ls". */
  cmd: string;
  /** One-line tagline. */
  short: string;
  /** Longer description shown when expanded. */
  long: string;
  /** Concrete example invocations, e.g. ["ls -la", "ls -a /tmp"]. */
  examples: string[];
  /** Grouping in the cheatsheet UI. */
  category: CheatCategory;
  /** Free-text search aliases. */
  keywords: string[];
}

export const CHEATSHEET: CheatEntry[] = [
  // Navigation
  {
    cmd: 'pwd',
    short: 'Print working directory',
    long: 'Shows the absolute path of the directory you are currently in.',
    examples: ['pwd'],
    category: 'Navigation',
    keywords: ['where', 'directory', 'path', 'current'],
  },
  {
    cmd: 'cd',
    short: 'Change directory',
    long: 'Moves you into a different directory. Use `cd ..` to go up one level, `cd ~` to jump home, or `cd -` to flip back to the previous directory.',
    examples: ['cd projects', 'cd ..', 'cd ~', 'cd /tmp'],
    category: 'Navigation',
    keywords: ['change', 'move', 'navigate', 'directory'],
  },
  {
    cmd: 'ls',
    short: 'List directory contents',
    long: 'Lists files and folders. `-l` shows a long listing with permissions, owner and size. `-a` includes hidden files (those starting with a dot).',
    examples: ['ls', 'ls -l', 'ls -la', 'ls /etc'],
    category: 'Navigation',
    keywords: ['list', 'files', 'directory', 'contents'],
  },

  // Files
  {
    cmd: 'mkdir',
    short: 'Make a directory',
    long: 'Creates a new directory. `-p` (parents) creates any missing intermediate directories and silently succeeds if the target already exists.',
    examples: ['mkdir lab', 'mkdir -p a/b/c'],
    category: 'Files',
    keywords: ['make', 'create', 'directory', 'folder'],
  },
  {
    cmd: 'touch',
    short: 'Create an empty file (or update its timestamp)',
    long: 'Creates an empty file if it does not exist, otherwise updates the modified time of the existing file.',
    examples: ['touch notes.txt'],
    category: 'Files',
    keywords: ['create', 'file', 'empty', 'timestamp'],
  },
  {
    cmd: 'cp',
    short: 'Copy files and directories',
    long: 'Copies a file to a new location. `-r` is required to copy a directory recursively.',
    examples: ['cp notes.txt copy.txt', 'cp -r src backup'],
    category: 'Files',
    keywords: ['copy', 'duplicate', 'file', 'directory'],
  },
  {
    cmd: 'mv',
    short: 'Move or rename files and directories',
    long: 'Renames a file or moves it to a new location. Works for both files and directories — there is no separate `rename` command.',
    examples: ['mv notes.txt renamed.txt', 'mv report.txt archive/'],
    category: 'Files',
    keywords: ['move', 'rename'],
  },
  {
    cmd: 'rm',
    short: 'Remove files or directories',
    long: 'Deletes a file. `-r` deletes a directory and everything inside it. `-f` skips the confirmation prompt. Be careful: there is no recycle bin.',
    examples: ['rm notes.txt', 'rm -r lab', 'rm -rf build'],
    category: 'Files',
    keywords: ['remove', 'delete', 'trash'],
  },
  {
    cmd: 'rmdir',
    short: 'Remove empty directories',
    long: 'Like `rm -r`, but refuses to delete a directory that still contains files. Safer for scripts.',
    examples: ['rmdir old-logs', 'rmdir -p a/b/c'],
    category: 'Files',
    keywords: ['remove', 'delete', 'directory', 'empty'],
  },
  {
    cmd: 'install',
    short: 'Copy a file into place (and create dirs with -D)',
    long: 'Copies a source file to a destination, optionally creating any missing intermediate directories (`-D`). The in-browser sandbox runs it as a safety-first copy.',
    examples: ['install -D src/header.h /usr/include/header.h'],
    category: 'Files',
    keywords: ['install', 'copy', 'deploy', 'header'],
  },
  {
    cmd: 'mktemp',
    short: 'Create a temporary file in /tmp',
    long: 'Makes a fresh empty file in `/tmp` whose name ends with a random suffix, and prints the path. Great for shell scripts that need scratch space.',
    examples: ['mktemp', 'mktemp tmp.XXXXXXXX'],
    category: 'Files',
    keywords: ['temp', 'temporary', 'scratch', 'random'],
  },
  {
    cmd: 'truncate',
    short: 'Shrink or extend a file to a given size (-s N)',
    long: 'Sets a file to exactly N bytes. If the file was longer it is cut; if shorter, the new bytes are null-padded. Useful for log rotation in scripts.',
    examples: ['truncate -s 0 app.log', 'truncate -s 1M image.bin'],
    category: 'Files',
    keywords: ['truncate', 'size', 'shrink', 'extend', 'log'],
  },
  {
    cmd: 'readlink',
    short: 'Print the value of a symbolic link',
    long: 'In the in-browser sandbox there are no real symlinks, so this prints the path you pass. Provided for script compatibility.',
    examples: ['readlink /usr/bin/python'],
    category: 'Files',
    keywords: ['symlink', 'link', 'target'],
  },
  {
    cmd: 'du',
    short: 'Estimate file / directory space usage',
    long: 'Walks a path and prints the total bytes it uses. `-h` switches to human units (K, M, G), `-s` prints only the summary line.',
    examples: ['du -sh projects', 'du -h --max-depth=1'],
    category: 'Files',
    keywords: ['disk', 'usage', 'size', 'recursive'],
  },
  {
    cmd: 'fileinfo',
    short: 'Show a compact summary of a file',
    long: 'Prints size, line count, word count and the (sandbox) last-modified time. The in-browser equivalent of `stat` for a quick glance.',
    examples: ['fileinfo notes.txt'],
    category: 'Files',
    keywords: ['file', 'info', 'summary', 'metadata'],
  },
  {
    cmd: 'ln',
    short: 'Create a link between files (simulated)',
    long: 'Simulated. In a real Linux system `ln -s` makes a symbolic link, `ln` (no flag) makes a hard link. The sandbox just acknowledges the request.',
    examples: ['ln -s config.txt config.link'],
    category: 'Files',
    keywords: ['link', 'symlink', 'hardlink'],
  },
  {
    cmd: 'find',
    short: 'Find files by name (supports -name <glob>)',
    long: 'Walks a directory tree and prints the paths that match. `-name "*.log"` is the most common use; supports `*` and `?` wildcards.',
    examples: ['find .', 'find /etc -name "*.conf"'],
    category: 'Search',
    keywords: ['find', 'search', 'glob', 'recursive', 'walk'],
  },
  {
    cmd: 'tree',
    short: 'Display a directory tree',
    long: 'Renders a pretty ASCII tree of the directory starting at the given path. Pure visualisation — no flags supported in the sandbox.',
    examples: ['tree', 'tree projects'],
    category: 'Inspection',
    keywords: ['tree', 'directory', 'structure', 'visualise'],
  },
  {
    cmd: 'stat',
    short: 'Display file status',
    long: 'Prints size, permissions, inode (simulated) and modification time. Verbose alternative to `ls -l`.',
    examples: ['stat notes.txt', 'stat /etc/passwd'],
    category: 'Inspection',
    keywords: ['stat', 'metadata', 'inode', 'permissions', 'mtime'],
  },
  {
    cmd: 'file',
    short: 'Determine file type',
    long: 'Sniffs the contents and prints what kind of file it is: ASCII text, empty, directory, or which interpreter a `#!/...` shebang points to.',
    examples: ['file notes.txt', 'file /usr/bin/ls'],
    category: 'Inspection',
    keywords: ['file', 'type', 'detect', 'magic', 'shebang'],
  },
  {
    cmd: 'basename',
    short: 'Strip the directory part of a path',
    long: 'Prints only the final filename component. Useful in shell loops over `find` results.',
    examples: ['basename /etc/nginx/nginx.conf'],
    category: 'Inspection',
    keywords: ['basename', 'filename', 'strip', 'path'],
  },
  {
    cmd: 'dirname',
    short: 'Strip the last component of a path',
    long: 'Prints everything except the final filename component — the directory portion of the path.',
    examples: ['dirname /etc/nginx/nginx.conf'],
    category: 'Inspection',
    keywords: ['dirname', 'path', 'directory'],
  },
  {
    cmd: 'realpath',
    short: 'Print the resolved absolute path',
    long: 'Resolves any `.`, `..`, or relative segments and prints a clean absolute path.',
    examples: ['realpath ../notes.txt', 'realpath ~/projects'],
    category: 'Inspection',
    keywords: ['realpath', 'absolute', 'path', 'resolve'],
  },
  {
    cmd: 'diff',
    short: 'Compare two files line by line',
    long: 'Walks both files and prints lines that differ, prefixed with `<` (first file) or `>` (second file). When files match, prints `(files are identical)`.',
    examples: ['diff old.txt new.txt'],
    category: 'Inspection',
    keywords: ['diff', 'compare', 'difference', 'patch'],
  },
  {
    cmd: 'tail',
    short: 'Show the last lines of a file',
    long: 'By default prints the last 10 lines. Pass `-n N` to change the count. Combine with `-f` (simulated) to follow a growing log file.',
    examples: ['tail notes.txt', 'tail -n 5 /var/log/syslog'],
    category: 'Inspection',
    keywords: ['end', 'last', 'lines', 'log', 'follow'],
  },
  {
    cmd: 'grep',
    short: 'Search text for a pattern (supports -i -v -n)',
    long: 'Prints lines that match a pattern. `-i` ignores case, `-v` inverts the match, `-n` prefixes each hit with its line number. Combine with `|` to filter any command’s output.',
    examples: ['grep error app.log', 'grep -in "TODO" notes.txt', 'cat app.log | grep 500'],
    category: 'Search',
    keywords: ['grep', 'search', 'pattern', 'regex', 'match', 'filter'],
  },
  {
    cmd: 'sort',
    short: 'Sort lines of text (supports -r -n -u)',
    long: 'Orders lines alphabetically by default. `-n` sorts numerically, `-r` reverses, `-u` keeps only unique lines.',
    examples: ['sort names.txt', 'sort -nr scores.txt', 'sort -u tags.txt'],
    category: 'Text',
    keywords: ['sort', 'order', 'alphabetical', 'numeric', 'unique'],
  },
  {
    cmd: 'uniq',
    short: 'Remove adjacent duplicate lines (supports -c -i)',
    long: 'Collapses runs of identical adjacent lines into one. For a global unique pass, pipe through `sort` first: `sort file | uniq`. `-c` prefixes each line with a count.',
    examples: ['uniq -c access.log', 'sort tags.txt | uniq'],
    category: 'Text',
    keywords: ['uniq', 'unique', 'duplicate', 'dedupe'],
  },
  {
    cmd: 'cut',
    short: 'Cut fields or characters from input',
    long: 'Splits each line by a delimiter (`-d`, default Tab) and prints the chosen fields (`-f`) or character positions (`-c`). Lists like `1,3-5` are supported.',
    examples: ['cut -d: -f1 /etc/passwd', 'cut -c1-10 file.txt'],
    category: 'Text',
    keywords: ['cut', 'field', 'column', 'delimiter', 'csv'],
  },
  {
    cmd: 'tr',
    short: 'Translate or delete characters',
    long: 'Maps characters in SET1 to characters in SET2 (one-to-one, by position). `-d` deletes the listed characters instead. Reads from a file argument or piped stdin.',
    examples: ['tr a-z A-Z < file.txt', 'tr -d "\\r" < dos.txt'],
    category: 'Text',
    keywords: ['tr', 'translate', 'delete', 'lowercase', 'uppercase'],
  },
  {
    cmd: 'tac',
    short: 'Print lines in reverse order',
    long: 'Reads a file and prints its lines from bottom to top. `cat` reversed, character-by-character.',
    examples: ['tac notes.txt'],
    category: 'Text',
    keywords: ['tac', 'reverse', 'lines'],
  },
  {
    cmd: 'rev',
    short: 'Reverse each line of input',
    long: 'Reads input and prints each line with its characters in reverse order. Lines themselves stay in order.',
    examples: ['rev names.txt'],
    category: 'Text',
    keywords: ['rev', 'reverse', 'characters', 'mirror'],
  },
  {
    cmd: 'nl',
    short: 'Number lines of input',
    long: 'Prefixes each non-empty line with its 1-based line number, right-aligned in 6 columns. Pair with `cat` to get a numbered listing.',
    examples: ['nl notes.txt', 'cat notes.txt | nl'],
    category: 'Text',
    keywords: ['nl', 'number', 'lines', 'enumerate'],
  },
  {
    cmd: 'paste',
    short: 'Merge lines of files side by side (-d delim)',
    long: 'Reads two or more files in parallel and joins their lines column-by-column with a delimiter (default Tab).',
    examples: ['paste names.txt phones.txt', 'paste -d, a.csv b.csv'],
    category: 'Text',
    keywords: ['paste', 'merge', 'columns', 'csv'],
  },
  {
    cmd: 'join',
    short: 'Join two files on a common field',
    long: 'Merges two files by matching the first whitespace-separated field of each line. Both files must be sorted on that field.',
    examples: ['join users.txt groups.txt'],
    category: 'Text',
    keywords: ['join', 'merge', 'sql', 'relational'],
  },
  {
    cmd: 'md5sum',
    short: 'Print MD5-style digests of files',
    long: 'Hashes each file and prints a 32-hex digest followed by the filename. Use it to spot-check that a file has not changed. (Sandbox: non-cryptographic.)',
    examples: ['md5sum *.iso'],
    category: 'Inspection',
    keywords: ['md5', 'hash', 'checksum', 'digest', 'verify'],
  },
  {
    cmd: 'sha256sum',
    short: 'Print SHA-256-style digests of files',
    long: 'Hashes each file and prints a 64-hex digest followed by the filename. Stronger than MD5 for tamper detection. (Sandbox: non-cryptographic.)',
    examples: ['sha256sum backup.tar'],
    category: 'Inspection',
    keywords: ['sha256', 'hash', 'checksum', 'digest', 'verify'],
  },
  {
    cmd: 'strings',
    short: 'Print printable strings (≥4 chars) from a file',
    long: 'Pulls out runs of printable ASCII at least 4 characters long. Classic tool for inspecting binary blobs.',
    examples: ['strings app.bin | less'],
    category: 'Inspection',
    keywords: ['strings', 'binary', 'ascii', 'extract'],
  },
  {
    cmd: 'od',
    short: 'Dump file in octal / hex / chars',
    long: 'Prints a numbered byte dump of the file. `-x` shows hex, `-c` shows printable characters (escapes for control bytes), default is octal.',
    examples: ['od -c notes.txt', 'od -x notes.txt'],
    category: 'Inspection',
    keywords: ['od', 'octal', 'hex', 'dump', 'bytes'],
  },
  {
    cmd: 'sed',
    short: 'Stream editor — supports s/find/replace/[g]',
    long: 'Applies a substitution expression to one or more files. The sandbox only supports the `s/find/replace/g` form (no addresses, no other commands). Add `g` to replace every match on a line.',
    examples: ['sed "s/old/new/g" notes.txt', "sed 's/foo/bar/' file.txt"],
    category: 'Text',
    keywords: ['sed', 'substitute', 'replace', 'stream', 'editor'],
  },
  {
    cmd: 'awk',
    short: 'Simple awk — `awk "{print $N}"` prints field N',
    long: 'The sandbox accepts the most common form: `awk "{print $N}" file` prints whitespace-separated field N of every line. `$0` prints the whole line.',
    examples: ['awk "{print $1}" access.log', 'awk "{print $0}" notes.txt'],
    category: 'Text',
    keywords: ['awk', 'field', 'column', 'gawk'],
  },
  {
    cmd: 'xxd',
    short: 'Hex dump of a file',
    long: 'Prints a hex+ASCII view of the file, 16 bytes per line. Useful for inspecting binary data and reverse engineering.',
    examples: ['xxd app.bin | head'],
    category: 'Inspection',
    keywords: ['xxd', 'hex', 'dump', 'binary'],
  },
  {
    cmd: 'base64',
    short: 'base64 encode or decode',
    long: 'Reads a file and either base64-encodes it (default) or decodes it (`-d`). Handy for embedding binary in JSON or copying certs as text.',
    examples: ['base64 photo.png', 'base64 -d ciphertext.txt'],
    category: 'Text',
    keywords: ['base64', 'encode', 'decode', 'binary'],
  },
  {
    cmd: 'tee',
    short: 'Read stdin, write to file and stdout (-a appends)',
    long: 'Splits a pipeline: the data flows through to stdout and is also written to one or more files. `-a` appends instead of overwriting.',
    examples: ['echo hello | tee out.txt', 'cat log | tee -a all.log | grep ERROR'],
    category: 'Text',
    keywords: ['tee', 'pipe', 'split', 'tee off'],
  },
  {
    cmd: 'xargs',
    short: 'Build and execute command lines (simulated)',
    long: 'Takes whitespace-separated tokens from stdin and runs the given command once per token, appending the token as the last argument. Lets you turn `find` output into a batch job.',
    examples: ['find . -name "*.log" | xargs rm', 'echo "a b c" | xargs echo item:'],
    category: 'Text',
    keywords: ['xargs', 'batch', 'pipe', 'arguments'],
  },
  {
    cmd: 'printf',
    short: 'Format and print data',
    long: 'Like `echo` but with C-style format specifiers. `%s` inserts the next argument as a string, `%d` parses the next argument as an integer. Useful in scripts where you need exact control.',
    examples: ['printf "hello %s\\n" world', 'printf "%d + %d = %d\\n" 1 2 3'],
    category: 'Editing',
    keywords: ['printf', 'format', 'template', 'string'],
  },
  {
    cmd: 'yes',
    short: 'Print a string repeatedly',
    long: 'Echoes its argument (or `y`) on repeat, forever in a real shell. The sandbox prints five lines and a `... (truncated)` marker so it does not flood the terminal.',
    examples: ['yes', 'yes "I agree" | head -n 3'],
    category: 'Editing',
    keywords: ['yes', 'repeat', 'confirm'],
  },
  {
    cmd: 'history',
    short: 'Show recent commands',
    long: 'Prints the in-memory history of commands you have run in the current sandbox session, numbered so you can refer to them.',
    examples: ['history', 'history | tail -n 5'],
    category: 'Help',
    keywords: ['history', 'recall', 'previous', 'replay'],
  },
  {
    cmd: 'env',
    short: 'Print environment variables',
    long: 'Lists all variables currently set in the shell’s environment, one per line as `NAME=value`. Use `export NAME=value` to set one.',
    examples: ['env', 'env | grep PATH'],
    category: 'System',
    keywords: ['env', 'environment', 'variables', 'export'],
  },
  {
    cmd: 'export',
    short: 'Set an environment variable',
    long: 'Adds (or updates) a variable in the shell’s environment. Format is `export NAME=value`. Variables set this way are visible to subsequent commands in the same session.',
    examples: ['export EDITOR=vim', 'export PATH="$HOME/bin:$PATH"'],
    category: 'System',
    keywords: ['export', 'set', 'variable', 'environment'],
  },
  {
    cmd: 'exit',
    short: 'Exit the shell (simulated)',
    long: 'Acknowledges the request and prints `logout`. The in-browser shell cannot really be closed — refresh the page to start a new session.',
    examples: ['exit'],
    category: 'System',
    keywords: ['exit', 'quit', 'logout', 'bye'],
  },
  {
    cmd: 'sleep',
    short: 'Pause for N seconds (simulated)',
    long: 'Real `sleep` waits in real time. The sandbox returns immediately so your lesson does not stall.',
    examples: ['sleep 1', 'sleep 0.5 && echo done'],
    category: 'System',
    keywords: ['sleep', 'wait', 'pause', 'delay'],
  },
  {
    cmd: 'true',
    short: 'Do nothing, successfully',
    long: 'Exits with status 0 and produces no output. Mostly useful in shell scripts: `while true; do ...; done`.',
    examples: ['true'],
    category: 'System',
    keywords: ['true', 'yes', 'success', 'noop'],
  },
  {
    cmd: 'false',
    short: 'Do nothing, unsuccessfully',
    long: 'Exits with a non-zero status and produces no output. Useful for testing `&&` / `||` chains.',
    examples: ['false || echo "fell through"'],
    category: 'System',
    keywords: ['false', 'no', 'failure', 'noop'],
  },
  {
    cmd: 'arch',
    short: 'Print machine architecture',
    long: 'Always reports `x86_64` in the sandbox. In real Linux it returns the CPU architecture of the host.',
    examples: ['arch'],
    category: 'System',
    keywords: ['arch', 'architecture', 'cpu', 'x86_64'],
  },
  {
    cmd: 'nproc',
    short: 'Print the number of processing units available',
    long: 'Returns the number of logical CPU cores. The sandbox reports 4. Used in build scripts to parallelise jobs.',
    examples: ['nproc', 'make -j$(nproc)'],
    category: 'System',
    keywords: ['nproc', 'cpu', 'cores', 'parallel'],
  },
  {
    cmd: 'lsblk',
    short: 'List block devices',
    long: 'Prints a tree of disks and partitions: names, sizes, mountpoints. Sandbox returns a small fixed example so you can recognise the columns.',
    examples: ['lsblk', 'lsblk -f'],
    category: 'System',
    keywords: ['lsblk', 'disk', 'partition', 'block', 'mount'],
  },
  {
    cmd: 'lscpu',
    short: 'Display CPU architecture information',
    long: 'Detailed dump of CPU model, cores, threads, cache sizes and feature flags. Sandbox returns a representative sample.',
    examples: ['lscpu'],
    category: 'System',
    keywords: ['lscpu', 'cpu', 'cache', 'flags'],
  },
  {
    cmd: 'lsmem',
    short: 'List the ranges of available memory',
    long: 'Summarises the physical memory ranges the kernel can see, with size and online/offline state. Sandbox returns a small sample.',
    examples: ['lsmem'],
    category: 'System',
    keywords: ['lsmem', 'memory', 'ram', 'numa'],
  },
  {
    cmd: 'lsof',
    short: 'List open files (simulated)',
    long: 'Classic sysadmin tool. In a real shell it lists every open file descriptor. The sandbox returns a few example entries so the columns make sense.',
    examples: ['lsof', 'lsof /etc/passwd'],
    category: 'System',
    keywords: ['lsof', 'open', 'files', 'fd', 'descriptor'],
  },
  {
    cmd: 'dmesg',
    short: 'Print the kernel ring buffer (simulated)',
    long: 'Shows the kernel’s recent log messages — useful for spotting hardware or driver problems at boot. Sandbox returns a representative slice.',
    examples: ['dmesg', 'dmesg | grep -i usb'],
    category: 'System',
    keywords: ['dmesg', 'kernel', 'log', 'boot'],
  },
  {
    cmd: 'last',
    short: 'Show last logged-in users (simulated)',
    long: 'Reads `/var/log/wtmp` (sandbox: a small static sample) and prints the recent login history, with session durations.',
    examples: ['last', 'last learner'],
    category: 'System',
    keywords: ['last', 'login', 'history', 'wtmp'],
  },
  {
    cmd: 'who',
    short: 'Show who is logged on',
    long: 'Prints one line per currently logged-in user: username, terminal, login time, and remote host (in parentheses).',
    examples: ['who', 'who -b'],
    category: 'System',
    keywords: ['who', 'logged in', 'users', 'sessions'],
  },
  {
    cmd: 'groups',
    short: 'Print group memberships for a user',
    long: 'With no argument, lists the groups of the current user. With a username, lists that user’s groups.',
    examples: ['groups', 'groups root'],
    category: 'Permissions',
    keywords: ['groups', 'membership', 'user', 'gid'],
  },
  {
    cmd: 'logname',
    short: "Return the user's login name",
    long: 'Prints the account name that was used to log into the current session, even after a `su` switch.',
    examples: ['logname'],
    category: 'System',
    keywords: ['logname', 'login', 'user', 'identity'],
  },
  {
    cmd: 'vmstat',
    short: 'Report virtual memory statistics',
    long: 'A one-line snapshot of process, memory, swap, I/O and CPU activity. Sandbox returns a representative line.',
    examples: ['vmstat', 'vmstat 2'],
    category: 'System',
    keywords: ['vmstat', 'memory', 'swap', 'cpu', 'stats'],
  },
  {
    cmd: 'iostat',
    short: 'Report CPU and I/O statistics',
    long: 'Per-device and CPU utilisation numbers — useful for spotting I/O bottlenecks. Sandbox returns a representative table.',
    examples: ['iostat', 'iostat -xz 2'],
    category: 'System',
    keywords: ['iostat', 'io', 'cpu', 'disk', 'stats'],
  },
  {
    cmd: 'history_stats',
    short: 'Show most-used commands from this session',
    long: 'Tallies how many times each command appears in the current session’s history and ranks them. Great for spotting your habits.',
    examples: ['history_stats'],
    category: 'Help',
    keywords: ['history', 'stats', 'most used', 'frequent'],
  },
  {
    cmd: 'kill',
    short: 'Send a signal to a process (simulated)',
    long: 'Takes a process ID and (in real shells) sends a signal — default `TERM`. Sandbox acknowledges the request and refuses non-numeric PIDs.',
    examples: ['kill 1234', 'kill -9 1234'],
    category: 'System',
    keywords: ['kill', 'signal', 'pid', 'terminate'],
  },
  {
    cmd: 'id',
    short: 'Print user identity',
    long: 'Prints the numeric UID, primary GID and the full list of group memberships for the current user.',
    examples: ['id', 'id root'],
    category: 'Permissions',
    keywords: ['id', 'uid', 'gid', 'identity'],
  },
  {
    cmd: 'which',
    short: 'Locate a command',
    long: 'Prints the absolute path of the executable that would run if you typed the command. In the sandbox it returns `/usr/bin/<cmd>` for known commands.',
    examples: ['which ls', 'which python'],
    category: 'System',
    keywords: ['which', 'locate', 'path', 'executable'],
  },
  {
    cmd: 'man',
    short: 'Show short help for a command',
    long: 'Like `help` but for one command at a time. Prints a small man-page-style summary (NAME, SYNOPSIS, DESCRIPTION).',
    examples: ['man ls', 'man grep'],
    category: 'Help',
    keywords: ['man', 'manual', 'help', 'docs'],
  },
  {
    cmd: 'sudo',
    short: 'Run a command as another user (simulated)',
    long: 'Pretends to elevate privileges and runs the command. The sandbox cannot really escalate, but the call is accepted so scripts keep working.',
    examples: ['sudo apt update', 'sudo systemctl restart nginx'],
    category: 'Permissions',
    keywords: ['sudo', 'root', 'privilege', 'admin'],
  },
  {
    cmd: 'nohup',
    short: 'Run a command immune to hangups (simulated)',
    long: 'In real Linux, `nohup` lets a command keep running after you log out. The sandbox acknowledges the request but does not background processes.',
    examples: ['nohup ./long-job.sh &'],
    category: 'System',
    keywords: ['nohup', 'background', 'hangup', 'detach'],
  },
  {
    cmd: 'ifconfig',
    short: 'Show network interfaces',
    long: 'Older but still-common tool for inspecting IP addresses, MAC addresses and packet counts per interface. (`ip addr` is the modern equivalent.)',
    examples: ['ifconfig', 'ifconfig eth0'],
    category: 'Network',
    keywords: ['ifconfig', 'network', 'interface', 'ip', 'mac'],
  },
  {
    cmd: 'ip',
    short: 'Show / manipulate routing (simulated, `ip addr`)',
    long: 'Modern replacement for `ifconfig`. The sandbox only supports `ip addr`, which prints the active IPv4 and IPv6 addresses per interface.',
    examples: ['ip addr', 'ip a'],
    category: 'Network',
    keywords: ['ip', 'addr', 'address', 'route', 'network'],
  },
  {
    cmd: 'ping',
    short: 'Ping a host (simulated)',
    long: 'Sends ICMP echo requests to a host and reports round-trip times. The sandbox simulates a successful three-packet exchange.',
    examples: ['ping learninx.dev', 'ping -c 3 1.1.1.1'],
    category: 'Network',
    keywords: ['ping', 'icmp', 'network', 'latency'],
  },
  {
    cmd: 'curl',
    short: 'Fetch a URL (simulated)',
    long: 'Pretends to make an HTTP request. `-I` / `--head` returns just the response headers; without it, returns a small HTML stub.',
    examples: ['curl https://learninx.dev', 'curl -I https://learninx.dev'],
    category: 'Network',
    keywords: ['curl', 'http', 'fetch', 'download', 'api'],
  },
  {
    cmd: 'wget',
    short: 'Download a URL to disk (simulated)',
    long: 'Like `curl`, but writes the response to a file by default. Sandbox reports a successful download with byte count.',
    examples: ['wget https://learninx.dev/index.html'],
    category: 'Network',
    keywords: ['wget', 'download', 'http', 'mirror'],
  },
  {
    cmd: 'ssh',
    short: 'Open a remote shell (simulated)',
    long: 'Pretends to log into the given host (format `user@host`) and prints a sample welcome banner.',
    examples: ['ssh learner@learninx.dev', 'ssh root@server.local'],
    category: 'Network',
    keywords: ['ssh', 'remote', 'login', 'shell'],
  },
  {
    cmd: 'chain',
    short: 'Chain commands with ;, &&, ||, and pipe with |',
    long: 'The Learninx shell supports the four classic control operators. `;` runs unconditionally. `&&` runs the right side only if the left side succeeded. `||` runs only on failure. `|` passes the left side’s stdout into the right side’s stdin.',
    examples: [
      'ls && echo done',
      'cat file | grep error',
      'false || echo "fell through"',
      'echo a ; echo b',
    ],
    category: 'Help',
    keywords: ['chain', 'and', 'or', 'pipe', 'semicolon', '&&', '||', '|'],
  },

  // Inspection
  {
    cmd: 'cat',
    short: 'Print the contents of a file',
    long: 'Writes the file to standard output. Great for short files. For longer files prefer `less` or `head` / `tail`.',
    examples: ['cat notes.txt', 'cat /etc/hostname'],
    category: 'Inspection',
    keywords: ['print', 'read', 'file', 'contents', 'show'],
  },
  {
    cmd: 'head',
    short: 'Show the first lines of a file',
    long: 'By default prints the first 10 lines. Pass `-n` to change the count.',
    examples: ['head notes.txt', 'head -n 5 /etc/passwd'],
    category: 'Inspection',
    keywords: ['start', 'first', 'lines', 'file'],
  },
  {
    cmd: 'wc',
    short: 'Count lines, words and bytes',
    long: 'By default prints three numbers: lines, words, bytes. Common flags: `-l` (lines only), `-w` (words only), `-c` (bytes only).',
    examples: ['wc notes.txt', 'wc -l notes.txt'],
    category: 'Inspection',
    keywords: ['count', 'lines', 'words', 'bytes'],
  },

  // Editing
  {
    cmd: 'echo',
    short: 'Print text to the screen',
    long: 'Writes its arguments to standard output. Combine with `>` to write to a file or `>>` to append.',
    examples: ['echo hello', 'echo hello > notes.txt', 'echo more >> notes.txt'],
    category: 'Editing',
    keywords: ['print', 'text', 'write', 'redirect'],
  },
  {
    cmd: 'nano',
    short: 'Beginner-friendly text editor',
    long: 'In the sandbox, `nano file` prints a TUI-style view of the file and tells you which commands to use for real edits. Use `echo > file` to overwrite or `>>` to append.',
    examples: ['nano notes.txt'],
    category: 'Editing',
    keywords: ['editor', 'simple', 'text', 'beginner'],
  },
  {
    cmd: 'vi / vim',
    short: 'Modal text editor',
    long: 'In the sandbox this prints a TUI view and lists the editing commands. In a real terminal: press `i` to enter insert mode, `Esc` to leave, `:wq` to save and quit.',
    examples: ['vi notes.txt', 'vim notes.txt'],
    category: 'Editing',
    keywords: ['editor', 'vim', 'vi', 'modal', 'advanced'],
  },

  // Permissions
  {
    cmd: 'chmod',
    short: 'Change file permissions',
    long: 'Updates the read / write / execute bits. The octal form is easiest: 7 = rwx, 6 = rw-, 5 = r-x, 4 = r--, 0 = ---.',
    examples: ['chmod +x script.sh', 'chmod 755 script.sh', 'chmod 600 secret.txt'],
    category: 'Permissions',
    keywords: ['permissions', 'mode', 'rwx', 'octal'],
  },
  {
    cmd: 'ps',
    short: 'List running processes',
    long: 'Shows the processes started in the current sandbox shell. Informational only — you cannot kill other sessions.',
    examples: ['ps'],
    category: 'Permissions',
    keywords: ['processes', 'list', 'running'],
  },

  // System
  {
    cmd: 'uname',
    short: 'Print system information',
    long: 'Prints the kernel name. `-a` includes the version, architecture and hostname.',
    examples: ['uname', 'uname -a'],
    category: 'System',
    keywords: ['system', 'kernel', 'info', 'version'],
  },
  {
    cmd: 'uptime',
    short: 'Show how long the system has been up',
    long: 'Prints a short uptime line. In the sandbox this is a simulated value.',
    examples: ['uptime'],
    category: 'System',
    keywords: ['uptime', 'load', 'time'],
  },
  {
    cmd: 'free',
    short: 'Show memory usage',
    long: 'Prints total, used and free memory. `-h` switches to human-readable units (K, M, G).',
    examples: ['free', 'free -h'],
    category: 'System',
    keywords: ['memory', 'ram', 'usage'],
  },
  {
    cmd: 'df',
    short: 'Show disk space usage',
    long: 'Reports the filesystem disk space usage. `-h` switches to human-readable units.',
    examples: ['df', 'df -h'],
    category: 'System',
    keywords: ['disk', 'space', 'storage', 'filesystem'],
  },
  {
    cmd: 'whoami',
    short: 'Print the current user',
    long: 'Writes your current username. In the sandbox you are always `learner`.',
    examples: ['whoami'],
    category: 'System',
    keywords: ['user', 'current', 'identity'],
  },
  {
    cmd: 'hostname',
    short: 'Print the system hostname',
    long: 'Writes the name of the current machine.',
    examples: ['hostname'],
    category: 'System',
    keywords: ['host', 'machine', 'name'],
  },
  {
    cmd: 'date',
    short: 'Show the current date and time',
    long: 'Prints the current local date and time.',
    examples: ['date'],
    category: 'System',
    keywords: ['date', 'time', 'clock'],
  },
  {
    cmd: 'clear',
    short: 'Clear the terminal',
    long: 'Scrolls the terminal so the prompt sits at the top of the visible area. Shortcut: Ctrl+L.',
    examples: ['clear'],
    category: 'System',
    keywords: ['clear', 'reset', 'screen'],
  },
  {
    cmd: 'help',
    short: 'List available commands',
    long: 'Prints the full list of sandbox commands with one-line descriptions.',
    examples: ['help'],
    category: 'Help',
    keywords: ['help', 'list', 'commands'],
  },
  {
    cmd: 'top',
    short: 'Show running processes (read-only)',
    long: 'In the sandbox this prints a static snapshot of process activity. The full interactive `top` is not available in the in-browser shell.',
    examples: ['top'],
    category: 'Help',
    keywords: ['top', 'processes', 'monitor', 'tasks'],
  },

  // ───────────────────────────────────────────────────── More Navigation
  {
    cmd: 'pushd / popd / dirs',
    short: 'Directory stack (cd, but remembers where you came from)',
    long: 'In real shells, `pushd dir` jumps to a new directory and pushes the current one onto a stack, `popd` pops back, and `dirs` prints the stack. The Learninx shell has no real stack, so these are documented for reference — use `cd -` to flip back to the previous directory.',
    examples: ['pushd projects', 'popd', 'dirs'],
    category: 'Navigation',
    keywords: ['pushd', 'popd', 'dirs', 'stack', 'directory history'],
  },
  {
    cmd: 'locate',
    short: 'Find files by name using a prebuilt index',
    long: 'Real `locate` queries a database (usually updated nightly by `updatedb`) so it is far faster than `find`. The sandbox does not run it — use `find <path> -name "<glob>"` here.',
    examples: ['locate nginx.conf', 'locate -i readme.md'],
    category: 'Search',
    keywords: ['locate', 'index', 'database', 'mlocate', 'plocate'],
  },
  {
    cmd: 'whereis',
    short: 'Locate the binary, source and man page for a command',
    long: 'Returns the absolute paths of the executable, its source file (if any) and its man page. The sandbox only simulates the binary path.',
    examples: ['whereis ls', 'whereis grep'],
    category: 'Search',
    keywords: ['whereis', 'locate', 'binary', 'man page', 'source'],
  },
  {
    cmd: 'type',
    short: 'Explain how a name would be interpreted',
    long: 'Tells you whether a name is a builtin, an alias, a function, or an external command on `$PATH`. In a real shell: `type -a cd` shows all matches.',
    examples: ['type cd', 'type ls', 'type -a echo'],
    category: 'Help',
    keywords: ['type', 'builtin', 'alias', 'function', 'command'],
  },

  // ──────────────────────────────────────────────────────── More Files
  {
    cmd: 'rsync',
    short: 'Fast incremental file transfer / sync',
    long: 'Syncs files between two paths, copying only what changed. Flags to remember: `-a` (archive, preserves perms/times), `-v` (verbose), `--dry-run` (preview), `--delete` (mirror deletions). Not implemented in the sandbox — shown for cheatsheet completeness.',
    examples: ['rsync -av src/ backup/', 'rsync -av --delete src/ dest/'],
    category: 'Files',
    keywords: ['rsync', 'sync', 'mirror', 'incremental', 'backup'],
  },
  {
    cmd: 'rename',
    short: 'Bulk-rename files with a Perl regex',
    long: 'Debian/Ubuntu `rename` (`prename`) takes a Perl substitution and applies it to every filename you pass. Powerful but easy to misuse — always run without the `-f` flag first to preview.',
    examples: ['rename "s/.txt/.md/" *.txt', 'rename "y/a-z/A-Z/" *.txt'],
    category: 'Files',
    keywords: ['rename', 'prename', 'bulk', 'rename', 'regex'],
  },
  {
    cmd: 'chown',
    short: 'Change file owner and group',
    long: 'Sets the user and (optionally) the group of a file. `chown user:group file` sets both at once. Requires root in a real shell — sandbox is informational.',
    examples: ['chown learner notes.txt', 'chown learner:staff notes.txt', 'chown -R root /etc/app'],
    category: 'Permissions',
    keywords: ['chown', 'owner', 'group', 'permissions', 'root'],
  },
  {
    cmd: 'chgrp',
    short: 'Change the group ownership of a file',
    long: 'Like `chown :group file` but only changes the group. Useful when you want to share a file with a project team without touching the owner.',
    examples: ['chgrp staff notes.txt', 'chgrp -R devs project/'],
    category: 'Permissions',
    keywords: ['chgrp', 'group', 'ownership', 'permissions'],
  },
  {
    cmd: 'umask',
    short: 'Default permission mask for new files',
    long: 'Returns the mask subtracted from 0666 (files) and 0777 (dirs) when new files are created. Default 022 means new files come out as 0644. Set it per-session: `umask 077` for private files.',
    examples: ['umask', 'umask 077'],
    category: 'Permissions',
    keywords: ['umask', 'mask', 'default', 'permissions', 'mode'],
  },
  {
    cmd: 'chattr / lsattr',
    short: 'Change / list file attributes (ext2/3/4)',
    long: 'Lower-level than `chmod`. Lets you mark files immutable (`+i`), append-only (`+a`), or compress (`+c`). Requires root. Sandbox is informational.',
    examples: ['chattr +i /etc/passwd', 'lsattr notes.txt'],
    category: 'Permissions',
    keywords: ['chattr', 'lsattr', 'attribute', 'immutable', 'ext4'],
  },
  {
    cmd: 'stat (extended)',
    short: 'Use stat -c to format specific fields',
    long: 'Beyond just printing everything, `stat -c "%a %n"` prints the octal mode then the name — useful in scripts. The Learninx `stat` command accepts `-c` and a small set of format tokens.',
    examples: ['stat -c "%a %n" notes.txt', 'stat -c "%s" image.png'],
    category: 'Inspection',
    keywords: ['stat', 'format', 'field', 'octal mode', 'size'],
  },
  {
    cmd: 'sync',
    short: 'Flush filesystem buffers to disk',
    long: 'Forces all pending writes in memory to be written to the disk(s). Run before risky operations or as a final step in shutdown scripts. Sandbox no-op.',
    examples: ['sync'],
    category: 'System',
    keywords: ['sync', 'flush', 'buffer', 'disk', 'write barrier'],
  },

  // ────────────────────────────────────────────── More Text processing
  {
    cmd: 'column',
    short: 'Format input as aligned columns (-t table)',
    long: 'Reads whitespace- or delimiter-separated input and re-emits it in neat aligned columns. `-t` auto-detects column widths; `-s` changes the delimiter; `-o` sets a separator for the output.',
    examples: ['cat data.txt | column -t', 'cut -d: -f1,6 /etc/passwd | column -t -s:'],
    category: 'Text',
    keywords: ['column', 'align', 'table', 'format', 'tabular'],
  },
  {
    cmd: 'expand / unexpand',
    short: 'Convert tabs to spaces (or back)',
    long: '`expand` replaces TAB characters with spaces (default 8). `unexpand` does the reverse — useful when pasting into code that disallows tabs.',
    examples: ['expand notes.txt', 'unexpand -t 4 notes.txt'],
    category: 'Text',
    keywords: ['expand', 'unexpand', 'tabs', 'spaces', 'whitespace'],
  },
  {
    cmd: 'fmt',
    short: 'Reformat text to fit a width',
    long: 'Reflows long lines so they fit within a maximum width (default 75). Keeps paragraph breaks intact. Pair with `pr` for printable output.',
    examples: ['fmt notes.txt', 'fmt -w 80 essay.md'],
    category: 'Text',
    keywords: ['fmt', 'format', 'wrap', 'paragraph', 'reflow'],
  },
  {
    cmd: 'fold',
    short: 'Wrap each line at a width (no word awareness)',
    long: 'Like `fmt` but dumber: it wraps at an exact column, breaking words in half if needed. Use `-s` to break only on spaces.',
    examples: ['fold -w 40 notes.txt', 'fold -w 80 -s long.txt'],
    category: 'Text',
    keywords: ['fold', 'wrap', 'width', 'column', 'cut'],
  },
  {
    cmd: 'pr',
    short: 'Paginate text for printing',
    long: 'Adds headers, footers and page breaks to a text file so it can be printed or archived cleanly. `-l N` changes page length, `-w N` the width.',
    examples: ['pr notes.txt', 'pr -l 20 -w 60 essay.md'],
    category: 'Text',
    keywords: ['pr', 'print', 'paginate', 'header', 'page'],
  },
  {
    cmd: 'shuf',
    short: 'Shuffle lines randomly',
    long: 'Writes a random permutation of input lines. `-n N` prints only N of them. Great for picking a random sample or choosing a winner.',
    examples: ['shuf names.txt', 'shuf -n 1 names.txt', 'shuf -i 1-100 -n 5'],
    category: 'Text',
    keywords: ['shuf', 'shuffle', 'random', 'sample', 'pick'],
  },
  {
    cmd: 'seq',
    short: 'Print a numeric sequence (start [step] end)',
    long: 'Writes one number per line, from `start` (default 1) to `end`, optionally stepping by `step`. `-w` equalises widths with leading zeros.',
    examples: ['seq 5', 'seq 1 2 10', 'seq -w 1 10'],
    category: 'Text',
    keywords: ['seq', 'sequence', 'numbers', 'range', 'iterate'],
  },
  {
    cmd: 'factor',
    short: 'Prime-factor decomposition of an integer',
    long: 'For each input integer, prints the prime factors. `factor 60` → `60: 2 2 3 5`. Pure command-line arithmetic fun.',
    examples: ['factor 60', 'factor 17', 'echo 1024 | factor'],
    category: 'Text',
    keywords: ['factor', 'prime', 'math', 'arithmetic', 'number'],
  },
  {
    cmd: 'comm',
    short: 'Compare two sorted files line by line (3 columns)',
    long: 'Outputs three columns: lines only in the first file, lines only in the second, and lines in both. `-i` is a typo; use `-12` to suppress columns 1 and 2 and show only common lines.',
    examples: ['comm a.txt b.txt', 'comm -12 a.txt b.txt'],
    category: 'Text',
    keywords: ['comm', 'compare', 'set', 'intersection', 'difference'],
  },
  {
    cmd: 'tsort',
    short: 'Topological sort of a partial order',
    long: 'Reads pairs `A B` meaning `A must come before B` and prints a valid total order. Useful in build systems for figuring out which targets depend on which.',
    examples: ['tsort deps.txt', 'echo -e "b a\\nc b" | tsort'],
    category: 'Text',
    keywords: ['tsort', 'topological', 'order', 'dependency', 'graph'],
  },
  {
    cmd: 'iconv',
    short: 'Convert text between character encodings',
    long: 'Re-encodes text from one charset to another (e.g. UTF-8 ↔ Latin-1). `-l` lists all known encodings. Sandbox is informational.',
    examples: ['iconv -f UTF-8 -t ISO-8859-1 notes.txt', 'iconv -l'],
    category: 'Text',
    keywords: ['iconv', 'encoding', 'charset', 'utf-8', 'convert'],
  },
  {
    cmd: 'less / more',
    short: 'Page through a file one screen at a time',
    long: 'Sandbox stub — prints a TUI-style view of the file (just like `nano`). In a real terminal, `less file` lets you scroll with arrows, search with `/`, and quit with `q`.',
    examples: ['less notes.txt', 'more /etc/services'],
    category: 'Inspection',
    keywords: ['less', 'more', 'pager', 'scroll', 'view'],
  },

  // ───────────────────────────────────────────── More Search / filter
  {
    cmd: 'rg (ripgrep)',
    short: 'Fast recursive grep (typically faster than grep -r)',
    long: 'Default on many modern systems. Recursively greps a directory, respects `.gitignore`, and skips binary files automatically. Not in the sandbox; shown for cheatsheet completeness.',
    examples: ['rg TODO src/', 'rg -i error logs/', 'rg -n "fn main" .'],
    category: 'Search',
    keywords: ['rg', 'ripgrep', 'grep', 'fast', 'recursive', 'search'],
  },
  {
    cmd: 'ag (silver searcher)',
    short: 'Recursive grep, ignores .gitignore, very fast',
    long: 'A predecessor to `rg`. Same idea — recursive grep that skips ignored files. Not in the sandbox; included for reference.',
    examples: ['ag TODO src/', 'ag -i error logs/'],
    category: 'Search',
    keywords: ['ag', 'silver searcher', 'grep', 'recursive', 'search'],
  },
  {
    cmd: 'ack',
    short: 'grep replacement aimed at source code',
    long: 'Defaults to recursive search and skips VCS metadata dirs. Less popular than `ag` / `rg` now, but still in many tutorials.',
    examples: ['ack TODO src/', 'ack --perl "\\bTODO\\b"'],
    category: 'Search',
    keywords: ['ack', 'grep', 'source', 'recursive', 'search'],
  },
  {
    cmd: 'fgrep',
    short: 'grep with fixed strings (no regex)',
    long: '`grep -F` shortcut. Treats the pattern as a literal string, so no escaping needed for `.`, `*`, `(`, etc. Faster on huge inputs.',
    examples: ['grep -F "error: file not found" logs.txt', 'fgrep "[INFO]" app.log'],
    category: 'Search',
    keywords: ['fgrep', 'fixed', 'literal', 'grep', 'no regex'],
  },
  {
    cmd: 'egrep',
    short: 'grep with extended regex (same as grep -E)',
    long: 'Treats the pattern as an ERE — so `+`, `?`, `()`, `|` are metacharacters without a backslash. Modern usage is just `grep -E`.',
    examples: ['grep -E "err|warn" app.log', 'egrep "^[A-Z]+$" tokens.txt'],
    category: 'Search',
    keywords: ['egrep', 'ERE', 'extended regex', 'grep'],
  },
  {
    cmd: 'xargs (advanced)',
    short: 'Use -n, -I{}, -0 for safer batched commands',
    long: 'Advanced flags: `-n 2` runs the command two args at a time; `-I{}` replaces `{}` with the input (lets the placeholder sit anywhere); `-0` splits on NUL bytes (safe for filenames with spaces — pair with `find -print0`).',
    examples: ['find . -name "*.log" -print0 | xargs -0 rm', 'echo a b c | xargs -n1 echo got:'],
    category: 'Text',
    keywords: ['xargs', 'nul', 'print0', 'batch', 'placeholder'],
  },

  // ──────────────────────────────────────────────────────── More Network
  {
    cmd: 'nslookup / dig',
    short: 'DNS lookups (query name servers)',
    long: 'Both query DNS to resolve a hostname to an IP. `dig` is more verbose and scriptable; `nslookup` is shorter and more interactive-friendly. Sandbox informational.',
    examples: ['dig learninx.dev', 'nslookup learninx.dev', 'dig +short MX gmail.com'],
    category: 'Network',
    keywords: ['nslookup', 'dig', 'dns', 'lookup', 'mx', 'record'],
  },
  {
    cmd: 'traceroute',
    short: 'Show the path packets take to a host',
    long: 'Sends packets with increasing TTLs and lists each router that responds, showing where the route slows or fails. Sandbox informational.',
    examples: ['traceroute learninx.dev', 'traceroute -n 1.1.1.1'],
    category: 'Network',
    keywords: ['traceroute', 'trace', 'hop', 'router', 'path'],
  },
  {
    cmd: 'netstat / ss',
    short: 'Show open ports and active connections',
    long: '`ss` is the modern replacement for `netstat`. Common flags: `-tuln` (listening TCP/UDP, numeric), `-p` (show process), `-s` (summary stats).',
    examples: ['ss -tuln', 'netstat -tulnp', 'ss -s'],
    category: 'Network',
    keywords: ['netstat', 'ss', 'socket', 'port', 'listen', 'connection'],
  },
  {
    cmd: 'scp',
    short: 'Secure copy (over SSH)',
    long: 'Copies files between hosts using SSH for transport. Format: `scp source user@host:dest` or the reverse. `-r` recurses, `-P` sets a non-default port.',
    examples: ['scp notes.txt learner@server:~/notes.txt', 'scp -r ./project learner@server:~/'],
    category: 'Network',
    keywords: ['scp', 'copy', 'remote', 'ssh', 'secure'],
  },
  {
    cmd: 'sftp',
    short: 'Interactive FTP over SSH',
    long: 'Starts an interactive session for browsing and transferring files on a remote host. Commands: `get`, `put`, `ls`, `cd`, `bye`.',
    examples: ['sftp learner@server', 'sftp -P 2222 learner@server'],
    category: 'Network',
    keywords: ['sftp', 'ftp', 'ssh', 'transfer', 'remote'],
  },
  {
    cmd: 'telnet',
    short: 'Talk to a TCP port in plaintext',
    long: 'Old but still handy: `telnet host port` opens a raw TCP connection. Useful for hand-testing protocols like SMTP, HTTP, or Redis. Plaintext — do not use for anything sensitive.',
    examples: ['telnet learninx.dev 80', 'telnet mail.example.com 25'],
    category: 'Network',
    keywords: ['telnet', 'tcp', 'plaintext', 'smoke test', 'protocol'],
  },
  {
    cmd: 'nc (netcat)',
    short: 'Swiss-army knife for TCP and UDP',
    long: 'Read or write to any TCP/UDP port from the shell. `-l` listens, `-z` does a port scan, `-v` is verbose. Combine with `mkfifo` for quick file transfer.',
    examples: ['nc -lv 8080', 'nc -zv learninx.dev 443', 'echo hello | nc learninx.dev 80'],
    category: 'Network',
    keywords: ['nc', 'netcat', 'tcp', 'udp', 'port scan', 'socket'],
  },
  {
    cmd: 'ip (extended)',
    short: 'Routes, links and neighbour tables',
    long: 'Beyond `ip addr`, real Linux supports `ip route`, `ip link`, `ip neigh` and more. The Learninx sandbox only handles `ip addr` — other forms print `not implemented in sandbox`.',
    examples: ['ip route', 'ip link', 'ip neigh'],
    category: 'Network',
    keywords: ['ip', 'route', 'link', 'neigh', 'arp', 'network'],
  },
  {
    cmd: 'ss -tunap',
    short: 'List all sockets with owning processes',
    long: 'Power-user shortcut. `t` TCP, `u` UDP, `n` numeric, `a` all, `p` process — shows you what is listening and which PID owns it. Requires root for the `p` column.',
    examples: ['ss -tunap', 'ss -tunap '],
    category: 'Network',
    keywords: ['ss', 'sockets', 'listening', 'pid', 'process'],
  },

  // ──────────────────────────────────────────────────────── Archiving
  {
    cmd: 'tar',
    short: 'Tape archive — pack/unpack files (-c -x -t -z -j -J)',
    long: 'The classic archive tool. Common flag combinations: `-czf out.tgz files` (gzip-compressed create), `-xzf in.tgz` (extract), `-tzf in.tgz` (list contents). `-C` changes directory for the operation.',
    examples: [
      'tar -czf backup.tgz project/',
      'tar -xzf backup.tgz',
      'tar -tzf backup.tgz',
      'tar -cjf backup.tar.bz2 project/',
    ],
    category: 'Archiving',
    keywords: ['tar', 'archive', 'tape', 'tgz', 'tarball', 'extract'],
  },
  {
    cmd: 'gzip / gunzip',
    short: 'Compress / decompress a single file (.gz)',
    long: '`gzip file` replaces `file` with `file.gz`. `gunzip file.gz` does the reverse. Pair with `tar -czf` to get `.tar.gz` archives. `-k` keeps the original.',
    examples: ['gzip notes.txt', 'gunzip notes.txt.gz', 'gzip -k big.log'],
    category: 'Archiving',
    keywords: ['gzip', 'gunzip', 'gz', 'compress', 'decompress'],
  },
  {
    cmd: 'bzip2 / bunzip2',
    short: 'Higher-ratio compression than gzip (.bz2)',
    long: 'Slower but compresses better than `gzip`. Same interface: `bzip2 file`, `bunzip2 file.bz2`. Often seen as `.tar.bz2` or `.tbz2`.',
    examples: ['bzip2 big.log', 'bunzip2 big.log.bz2'],
    category: 'Archiving',
    keywords: ['bzip2', 'bunzip2', 'bz2', 'compress', 'decompress'],
  },
  {
    cmd: 'xz / unxz',
    short: 'LZMA compression — often the smallest (.xz)',
    long: 'Modern, high-ratio compressor. Common extension `.tar.xz` (used by many Linux kernel releases). Slower than gzip.',
    examples: ['xz image.iso', 'unxz image.iso.xz'],
    category: 'Archiving',
    keywords: ['xz', 'unxz', 'lzma', 'compress', 'decompress'],
  },
  {
    cmd: 'zip / unzip',
    short: 'Cross-platform archive format (.zip)',
    long: '`zip out.zip file` adds `file` to a new zip. `unzip in.zip` extracts. `-r` recurses, `-e` encrypts, `-l` lists. Common for sharing files with Windows users.',
    examples: ['zip -r project.zip project/', 'unzip project.zip -d ./out', 'unzip -l project.zip'],
    category: 'Archiving',
    keywords: ['zip', 'unzip', 'archive', 'cross platform', 'windows'],
  },
  {
    cmd: '7z / 7zz',
    short: '7-Zip — supports many formats, high compression',
    long: '`p7zip` provides `7z` on Linux. Compresses to `.7z` (often smallest) and can read `.zip`, `.tar.gz`, `.rar` and more. `a` adds, `x` extracts, `l` lists.',
    examples: ['7z a backup.7z project/', '7z x backup.7z', '7z l backup.7z'],
    category: 'Archiving',
    keywords: ['7z', '7zip', 'p7zip', 'archive', 'high compression'],
  },
  {
    cmd: 'unzip (flags)',
    short: 'Selective extraction and listing',
    long: 'Common flags: `-l` list, `-d DIR` extract into DIR, `-o` overwrite without prompt, `-n` never overwrite, `-p` print to stdout, `-q` quiet.',
    examples: ['unzip -l archive.zip', 'unzip -d ./out archive.zip', 'unzip -p archive.zip readme.txt'],
    category: 'Archiving',
    keywords: ['unzip', 'list', 'extract', 'directory', 'overwrite'],
  },
  {
    cmd: 'tar (advanced)',
    short: 'Exclude files, append, stream through a pipe',
    long: 'Useful extras: `--exclude="*.log"` skips matches; `-rf archive.tar newfile` appends to an existing archive; `--strip-components=N` strips N leading path components on extract; pipe to compress on the fly.',
    examples: [
      'tar -czf out.tgz --exclude="*.log" project/',
      'tar -xzf in.tgz --strip-components=1',
      'tar -cf - src/ | ssh user@host "tar -xf - -C /dest"',
    ],
    category: 'Archiving',
    keywords: ['tar', 'exclude', 'append', 'strip', 'pipe', 'ssh'],
  },
  {
    cmd: 'cpio',
    short: 'Copy files in / out of an archive (low-level)',
    long: 'Predecessor to `tar`; still used inside `initramfs` images. `find . | cpio -o > archive.cpio` creates one, `cpio -i < archive.cpio` extracts.',
    examples: ['find . | cpio -o > archive.cpio', 'cpio -id < archive.cpio'],
    category: 'Archiving',
    keywords: ['cpio', 'archive', 'initramfs', 'copy in', 'copy out'],
  },
  {
    cmd: 'zcat / zless / zgrep',
    short: 'Operate directly on gzip-compressed files',
    long: 'Family of helpers: `zcat file.gz` is `cat` for gzip; `zless file.gz` is `less`; `zgrep PATTERN file.gz` is `grep` — no manual decompression step needed.',
    examples: ['zcat app.log.gz', 'zless app.log.gz', 'zgrep ERROR app.log.gz'],
    category: 'Archiving',
    keywords: ['zcat', 'zless', 'zgrep', 'gzip', 'transparent'],
  },

  // ───────────────────────────────────────────── More Permissions & users
  {
    cmd: 'su',
    short: 'Switch user (default root)',
    long: 'With no argument, `su` opens a root shell. `su learner` switches to another user. The `-` flag also loads that user’s environment. Sandbox informational.',
    examples: ['su', 'su - learner', 'su -c "apt update" root'],
    category: 'Permissions',
    keywords: ['su', 'switch', 'user', 'root', 'login'],
  },
  {
    cmd: 'passwd',
    short: 'Change a user password',
    long: 'With no argument, changes the current user’s password. As root, `passwd learner` resets another user’s. Sandbox informational.',
    examples: ['passwd', 'passwd learner'],
    category: 'Permissions',
    keywords: ['passwd', 'password', 'change', 'user'],
  },
  {
    cmd: 'useradd / userdel / usermod',
    short: 'Manage user accounts',
    long: '`useradd name` creates a user, `userdel -r name` removes one (and their home), `usermod -aG group user` adds them to a group. All require root.',
    examples: ['useradd -m alice', 'usermod -aG sudo alice', 'userdel -r alice'],
    category: 'Permissions',
    keywords: ['useradd', 'userdel', 'usermod', 'account', 'user'],
  },
  {
    cmd: 'groupadd / groupdel',
    short: 'Add or remove groups',
    long: '`groupadd devs` creates a group, `groupdel devs` removes one. Pair with `usermod -aG` to add users to it.',
    examples: ['groupadd devs', 'groupdel devs'],
    category: 'Permissions',
    keywords: ['groupadd', 'groupdel', 'group', 'manage'],
  },
  {
    cmd: 'visudo',
    short: 'Safely edit the sudoers file',
    long: 'Opens `/etc/sudoers` in the system editor with a syntax check before saving — never edit that file with a regular editor. Sandbox informational.',
    examples: ['visudo', 'visudo -f /etc/sudoers.d/devs'],
    category: 'Permissions',
    keywords: ['visudo', 'sudoers', 'edit', 'root', 'admin'],
  },

  // ──────────────────────────────────────────────────────── More System
  {
    cmd: 'systemctl',
    short: 'Control systemd services (start/stop/enable/status)',
    long: 'Modern way to manage services. `systemctl status nginx` shows logs and state, `systemctl enable --now nginx` starts it and turns it on at boot. Not available in the sandbox.',
    examples: [
      'systemctl status nginx',
      'sudo systemctl restart sshd',
      'systemctl enable --now cron',
    ],
    category: 'System',
    keywords: ['systemctl', 'systemd', 'service', 'unit', 'daemon'],
  },
  {
    cmd: 'service',
    short: 'SysV-style service control',
    long: 'Older interface (`service nginx restart`) still works on most distros thanks to systemd compatibility shims. Prefer `systemctl` on new systems.',
    examples: ['service nginx status', 'sudo service ssh restart'],
    category: 'System',
    keywords: ['service', 'sysv', 'init', 'restart'],
  },
  {
    cmd: 'journalctl',
    short: 'Read the systemd journal (logs)',
    long: '`journalctl -u nginx` shows logs for one unit; `-f` follows; `--since "1 hour ago"` filters by time; `-p err` filters by priority.',
    examples: ['journalctl -u nginx -f', 'journalctl -p err --since today', 'journalctl --list-boots'],
    category: 'System',
    keywords: ['journalctl', 'journal', 'logs', 'systemd', 'unit'],
  },
  {
    cmd: 'crontab',
    short: 'Schedule recurring jobs',
    long: 'Edit with `crontab -e`, list with `crontab -l`. A line is `m h dom mon dow command`. `@reboot`, `@daily` etc. are shortcuts.',
    examples: ['crontab -l', 'crontab -e', '*/5 * * * * /opt/job.sh'],
    category: 'System',
    keywords: ['crontab', 'cron', 'schedule', 'recurring', 'job'],
  },
  {
    cmd: 'at',
    short: 'Schedule a one-shot job at a specific time',
    long: '`at 14:00` then type commands, Ctrl+D to finish. Unlike `cron`, jobs run once and disappear. `atq` lists pending, `atrm N` removes.',
    examples: ['at 14:00', 'atq', 'atrm 3'],
    category: 'System',
    keywords: ['at', 'schedule', 'one shot', 'batch', 'queue'],
  },
  {
    cmd: 'shutdown / reboot / halt / poweroff',
    short: 'Stop, restart, or power off the machine',
    long: '`shutdown -h now` halts immediately; `shutdown -r +5` reboots in 5 minutes; `reboot` and `poweroff` are short aliases. All require root in a real shell.',
    examples: ['sudo shutdown -h now', 'sudo reboot', 'sudo shutdown -r +5 "kernel update"'],
    category: 'System',
    keywords: ['shutdown', 'reboot', 'halt', 'poweroff', 'init'],
  },
  {
    cmd: 'init / runlevel / telinit',
    short: 'Legacy init control (SysV)',
    long: '`init 0` halts, `init 6` reboots, `runlevel` prints the current and previous level. Largely replaced by `systemctl`. Sandbox informational.',
    examples: ['runlevel', 'sudo init 6'],
    category: 'System',
    keywords: ['init', 'runlevel', 'telinit', 'sysv', 'legacy'],
  },
  {
    cmd: 'bg / fg / jobs / disown',
    short: 'Job control: move processes between background and foreground',
    long: 'Append `&` to start in background, `jobs` lists them, `fg %1` brings #1 to the front, `Ctrl+Z` suspends, `bg %1` resumes in background, `disown %1` detaches.',
    examples: ['sleep 60 &', 'jobs', 'fg %1', 'Ctrl+Z then bg %1'],
    category: 'System',
    keywords: ['bg', 'fg', 'jobs', 'disown', 'job control', 'background'],
  },
  {
    cmd: 'nice / renice',
    short: 'Run with adjusted scheduling priority (-20 highest, 19 lowest)',
    long: 'Default nice value is 0. `nice -n 10 make` runs `make` at lower priority so it does not starve interactive jobs. `renice` changes an existing process.',
    examples: ['nice -n 10 make', 'sudo renice -n -5 -p 1234'],
    category: 'System',
    keywords: ['nice', 'renice', 'priority', 'scheduler', 'cpu'],
  },
  {
    cmd: 'time',
    short: 'Measure how long a command takes',
    long: '`time command` reports wall time, user CPU time and system CPU time. The Learninx shell exposes a builtin `time`; the binary `/usr/bin/time -v` gives even more detail in real shells.',
    examples: ['time find / -name "*.log"', '/usr/bin/time -v make'],
    category: 'System',
    keywords: ['time', 'measure', 'benchmark', 'duration'],
  },
  {
    cmd: 'timeout',
    short: 'Run a command with a hard time limit',
    long: '`timeout 5s long-cmd` kills the command after 5 seconds. Sends `TERM` by default; `--signal=KILL` for a more aggressive end. Sandbox no-op.',
    examples: ['timeout 5s ping 8.8.8.8', 'timeout --signal=KILL 30s ./build.sh'],
    category: 'System',
    keywords: ['timeout', 'limit', 'kill', 'wall clock'],
  },
  {
    cmd: 'watch',
    short: 'Re-run a command every N seconds',
    long: '`watch -n 2 "df -h"` re-runs `df -h` every 2 seconds, highlighting changes. `-d` highlights differences between runs. Sandbox informational.',
    examples: ['watch -n 2 "df -h"', 'watch -d ls /tmp'],
    category: 'System',
    keywords: ['watch', 'repeat', 'monitor', 'diff'],
  },
  {
    cmd: 'lspci / lsusb / lsmod',
    short: 'List PCI / USB devices and loaded kernel modules',
    long: '`lspci` enumerates PCI/PCIe hardware, `lsusb` does USB, `lsmod` shows currently loaded kernel modules. All require a real kernel — sandbox prints a representative sample.',
    examples: ['lspci', 'lsusb', 'lsmod'],
    category: 'System',
    keywords: ['lspci', 'lsusb', 'lsmod', 'hardware', 'kernel', 'module'],
  },
  {
    cmd: 'modprobe / rmmod / insmod',
    short: 'Load / unload kernel modules',
    long: '`modprobe name` loads a module and its dependencies. `rmmod name` removes it. `insmod path.ko` loads by file path, no dependency resolution. All require root.',
    examples: ['sudo modprobe br_netfilter', 'sudo rmmod br_netfilter', 'sudo insmod /lib/modules/.../mymod.ko'],
    category: 'System',
    keywords: ['modprobe', 'rmmod', 'insmod', 'kernel module', 'driver'],
  },
  {
    cmd: 'strace / ltrace',
    short: 'Trace syscalls / library calls of a process',
    long: '`strace -e openat cmd` shows which files a command opens. `ltrace` does the same for library calls. Powerful debugging tools — slow the target down, so do not use in production.',
    examples: ['strace -e openat ls', 'strace -p 1234', 'ltrace ./a.out'],
    category: 'System',
    keywords: ['strace', 'ltrace', 'syscall', 'library', 'trace'],
  },
  {
    cmd: 'ulimit',
    short: 'Show or set per-process resource limits',
    long: 'Built-in. Common values: `-n` (open files), `-u` (max processes), `-t` (cpu seconds), `-v` (virtual memory). Adjusts limits for the current shell.',
    examples: ['ulimit -n', 'ulimit -n 4096', 'ulimit -a'],
    category: 'System',
    keywords: ['ulimit', 'limit', 'rlimit', 'resources', 'nofile'],
  },
  {
    cmd: 'alias / unalias',
    short: 'Define / remove a command shortcut',
    long: '`alias ll="ls -la"` defines a shortcut for the current shell. Add it to `~/.bashrc` to persist. `unalias ll` removes it.',
    examples: ['alias ll="ls -la"', 'alias gs="git status"', 'unalias ll'],
    category: 'Help',
    keywords: ['alias', 'unalias', 'shortcut', 'bashrc', 'shell'],
  },
  {
    cmd: 'source / .',
    short: 'Run a script in the current shell',
    long: '`source script.sh` (or its short form `. script.sh`) executes the file in the current shell, so its `export`s and `cd` stick. Without it, the script runs in a subshell.',
    examples: ['source ~/.bashrc', '. ./env.sh'],
    category: 'Help',
    keywords: ['source', 'dot', 'subshell', 'environment', 'script'],
  },
  {
    cmd: 'set / unset',
    short: 'Set or remove shell variables / options',
    long: 'Builtin. `set -e` aborts on any error, `set -u` errors on undefined variables, `set -x` prints each command before running. `set` alone lists all variables. `unset NAME` removes one.',
    examples: ['set -e', 'set -euxo pipefail', 'set +e', 'unset FOO'],
    category: 'Help',
    keywords: ['set', 'unset', 'option', 'errexit', 'nounset', 'xtrace'],
  },
  {
    cmd: 'hash',
    short: 'Show / clear the remembered $PATH cache',
    long: 'Bash caches the location of recently used commands. `hash` shows the cache; `hash -r` clears it (force re-resolution from `$PATH`). Useful after installing a new tool.',
    examples: ['hash', 'hash -r', 'hash -t ls'],
    category: 'Help',
    keywords: ['hash', 'cache', 'path', 'rehash'],
  },
  {
    cmd: 'fc',
    short: 'Fix Command — edit & re-run a previous command',
    long: '`fc` opens your last command in `$EDITOR`; save and quit to run it. `fc -l` lists recent commands (similar to history). Handy for editing long pipelines.',
    examples: ['fc', 'fc -l', 'fc 50 60'],
    category: 'Help',
    keywords: ['fc', 'fix command', 'edit', 'history', 'replay'],
  },
  {
    cmd: 'wait',
    short: 'Wait for background jobs to finish',
    long: '`wait` blocks until all background children of the current shell exit. `wait %1` waits for job #1. Returns the exit status of the waited-on job.',
    examples: ['sleep 10 &', 'wait', 'wait %1'],
    category: 'Help',
    keywords: ['wait', 'background', 'job', 'synchronise'],
  },
  {
    cmd: 'read',
    short: 'Read a line from stdin into a variable',
    long: 'Built-in. `read -p "name? " name` prompts and stores. `-s` silent (for passwords), `-r` raw (no backslash escapes), `-t N` timeout after N seconds.',
    examples: ['read -p "Name? " name', 'read -s -p "Password: " pw'],
    category: 'Editing',
    keywords: ['read', 'stdin', 'input', 'prompt', 'password'],
  },
  {
    cmd: 'test / [ ]',
    short: 'Evaluate a condition (used in if / while)',
    long: 'Returns success or failure based on a test. Common operators: `-f file` (is a file), `-d dir` (is a dir), `-z "$s"` (empty string), `n1 -eq n2`. `[` and `test` are the same program.',
    examples: ['[ -f notes.txt ] && echo yes', '[ "$x" = "y" ]', '[ -d /tmp ]'],
    category: 'Editing',
    keywords: ['test', 'bracket', 'if', 'condition', '[ ]'],
  },
  {
    cmd: 'exec',
    short: 'Replace the current shell with a command',
    long: '`exec vim` replaces the current shell — no return, no subshell. `exec > log.txt` redirects all subsequent stdout to a file without forking.',
    examples: ['exec vim notes.txt', 'exec > log.txt 2>&1'],
    category: 'Editing',
    keywords: ['exec', 'replace', 'redirect', 'shell'],
  },
];

export const CHEAT_CATEGORIES: CheatCategory[] = [
  'Navigation',
  'Files',
  'Inspection',
  'Editing',
  'Text',
  'Search',
  'Permissions',
  'Network',
  'Archiving',
  'System',
  'Help',
];

export function cheatMatches(entry: CheatEntry, q: string): boolean {
  if (!q) return true;
  const needle = q.toLowerCase();
  const haystack = [
    entry.cmd,
    entry.short,
    entry.long,
    entry.category,
    ...entry.examples,
    ...entry.keywords,
  ]
    .join(' ')
    .toLowerCase();
  return haystack.includes(needle);
}
