/**
 * Cheatsheet — structured reference of the commands supported by the
 * in-browser sandbox in `src/lib/shell/evaluator.ts`. The cheatsheet
 * page filters this list client-side.
 *
 * Keep this file dependency-free so it can be imported from server or
 * client components.
 */

export type CheatCategory =
  | 'Navigation'
  | 'Files'
  | 'Inspection'
  | 'Editing'
  | 'Permissions'
  | 'Text'
  | 'Search'
  | 'Network'
  | 'Archiving'
  | 'System'
  | 'Help';

export interface CheatEntry {
  /** Command name, e.g. "ls". */
  cmd: string;
  /** One-line tagline. */
  short: string;
  /** Longer description shown when expanded. */
  long: string;
  /** Concrete example invocations, e.g. ["ls -la", "ls -a /tmp"]. */
  examples: string[];
  /** Grouping in the cheatsheet UI. */
  category: CheatCategory;
  /** Free-text search aliases. */
  keywords: string[];
}

export const CHEATSHEET: CheatEntry[] = [
  // Navigation
  {
    cmd: 'pwd',
    short: 'Print working directory',
    long: 'Shows the absolute path of the directory you are currently in.',
    examples: ['pwd'],
    category: 'Navigation',
    keywords: ['where', 'directory', 'path', 'current'],
  },
  {
    cmd: 'cd',
    short: 'Change directory',
    long: 'Moves you into a different directory. Use `cd ..` to go up one level, `cd ~` to jump home, or `cd -` to flip back to the previous directory.',
    examples: ['cd projects', 'cd ..', 'cd ~', 'cd /tmp'],
    category: 'Navigation',
    keywords: ['change', 'move', 'navigate', 'directory'],
  },
  {
    cmd: 'ls',
    short: 'List directory contents',
    long: 'Lists files and folders. `-l` shows a long listing with permissions, owner and size. `-a` includes hidden files (those starting with a dot).',
    examples: ['ls', 'ls -l', 'ls -la', 'ls /etc'],
    category: 'Navigation',
    keywords: ['list', 'files', 'directory', 'contents'],
  },

  // Files
  {
    cmd: 'mkdir',
    short: 'Make a directory',
    long: 'Creates a new directory. `-p` (parents) creates any missing intermediate directories and silently succeeds if the target already exists.',
    examples: ['mkdir lab', 'mkdir -p a/b/c'],
    category: 'Files',
    keywords: ['make', 'create', 'directory', 'folder'],
  },
  {
    cmd: 'touch',
    short: 'Create an empty file (or update its timestamp)',
    long: 'Creates an empty file if it does not exist, otherwise updates the modified time of the existing file.',
    examples: ['touch notes.txt'],
    category: 'Files',
    keywords: ['create', 'file', 'empty', 'timestamp'],
  },
  {
    cmd: 'cp',
    short: 'Copy files and directories',
    long: 'Copies a file to a new location. `-r` is required to copy a directory recursively.',
    examples: ['cp notes.txt copy.txt', 'cp -r src backup'],
    category: 'Files',
    keywords: ['copy', 'duplicate', 'file', 'directory'],
  },
  {
    cmd: 'mv',
    short: 'Move or rename files and directories',
    long: 'Renames a file or moves it to a new location. Works for both files and directories — there is no separate `rename` command.',
    examples: ['mv notes.txt renamed.txt', 'mv report.txt archive/'],
    category: 'Files',
    keywords: ['move', 'rename'],
  },
  {
    cmd: 'rm',
    short: 'Remove files or directories',
    long: 'Deletes a file. `-r` deletes a directory and everything inside it. `-f` skips the confirmation prompt. Be careful: there is no recycle bin.',
    examples: ['rm notes.txt', 'rm -r lab', 'rm -rf build'],
    category: 'Files',
    keywords: ['remove', 'delete', 'trash'],
  },
  {
    cmd: 'rmdir',
    short: 'Remove empty directories',
    long: 'Like `rm -r`, but refuses to delete a directory that still contains files. Safer for scripts.',
    examples: ['rmdir old-logs', 'rmdir -p a/b/c'],
    category: 'Files',
    keywords: ['remove', 'delete', 'directory', 'empty'],
  },
  {
    cmd: 'install',
    short: 'Copy a file into place (and create dirs with -D)',
    long: 'Copies a source file to a destination, optionally creating any missing intermediate directories (`-D`). The in-browser sandbox runs it as a safety-first copy.',
    examples: ['install -D src/header.h /usr/include/header.h'],
    category: 'Files',
    keywords: ['install', 'copy', 'deploy', 'header'],
  },
  {
    cmd: 'mktemp',
    short: 'Create a temporary file in /tmp',
    long: 'Makes a fresh empty file in `/tmp` whose name ends with a random suffix, and prints the path. Great for shell scripts that need scratch space.',
    examples: ['mktemp', 'mktemp tmp.XXXXXXXX'],
    category: 'Files',
    keywords: ['temp', 'temporary', 'scratch', 'random'],
  },
  {
    cmd: 'truncate',
    short: 'Shrink or extend a file to a given size (-s N)',
    long: 'Sets a file to exactly N bytes. If the file was longer it is cut; if shorter, the new bytes are null-padded. Useful for log rotation in scripts.',
    examples: ['truncate -s 0 app.log', 'truncate -s 1M image.bin'],
    category: 'Files',
    keywords: ['truncate', 'size', 'shrink', 'extend', 'log'],
  },
  {
    cmd: 'readlink',
    short: 'Print the value of a symbolic link',
    long: 'In the in-browser sandbox there are no real symlinks, so this prints the path you pass. Provided for script compatibility.',
    examples: ['readlink /usr/bin/python'],
    category: 'Files',
    keywords: ['symlink', 'link', 'target'],
  },
  {
    cmd: 'du',
    short: 'Estimate file / directory space usage',
    long: 'Walks a path and prints the total bytes it uses. `-h` switches to human units (K, M, G), `-s` prints only the summary line.',
    examples: ['du -sh projects', 'du -h --max-depth=1'],
    category: 'Files',
    keywords: ['disk', 'usage', 'size', 'recursive'],
  },
  {
    cmd: 'fileinfo',
    short: 'Show a compact summary of a file',
    long: 'Prints size, line count, word count and the (sandbox) last-modified time. The in-browser equivalent of `stat` for a quick glance.',
    examples: ['fileinfo notes.txt'],
    category: 'Files',
    keywords: ['file', 'info', 'summary', 'metadata'],
  },
  {
    cmd: 'ln',
    short: 'Create a link between files (simulated)',
    long: 'Simulated. In a real Linux system `ln -s` makes a symbolic link, `ln` (no flag) makes a hard link. The sandbox just acknowledges the request.',
    examples: ['ln -s config.txt config.link'],
    category: 'Files',
    keywords: ['link', 'symlink', 'hardlink'],
  },
  {
    cmd: 'find',
    short: 'Find files by name (supports -name <glob>)',
    long: 'Walks a directory tree and prints the paths that match. `-name "*.log"` is the most common use; supports `*` and `?` wildcards.',
    examples: ['find .', 'find /etc -name "*.conf"'],
    category: 'Search',
    keywords: ['find', 'search', 'glob', 'recursive', 'walk'],
  },
  {
    cmd: 'tree',
    short: 'Display a directory tree',
    long: 'Renders a pretty ASCII tree of the directory starting at the given path. Pure visualisation — no flags supported in the sandbox.',
    examples: ['tree', 'tree projects'],
    category: 'Inspection',
    keywords: ['tree', 'directory', 'structure', 'visualise'],
  },
  {
    cmd: 'stat',
    short: 'Display file status',
    long: 'Prints size, permissions, inode (simulated) and modification time. Verbose alternative to `ls -l`.',
    examples: ['stat notes.txt', 'stat /etc/passwd'],
    category: 'Inspection',
    keywords: ['stat', 'metadata', 'inode', 'permissions', 'mtime'],
  },
  {
    cmd: 'file',
    short: 'Determine file type',
    long: 'Sniffs the contents and prints what kind of file it is: ASCII text, empty, directory, or which interpreter a `#!/...` shebang points to.',
    examples: ['file notes.txt', 'file /usr/bin/ls'],
    category: 'Inspection',
    keywords: ['file', 'type', 'detect', 'magic', 'shebang'],
  },
  {
    cmd: 'basename',
    short: 'Strip the directory part of a path',
    long: 'Prints only the final filename component. Useful in shell loops over `find` results.',
    examples: ['basename /etc/nginx/nginx.conf'],
    category: 'Inspection',
    keywords: ['basename', 'filename', 'strip', 'path'],
  },
  {
    cmd: 'dirname',
    short: 'Strip the last component of a path',
    long: 'Prints everything except the final filename component — the directory portion of the path.',
    examples: ['dirname /etc/nginx/nginx.conf'],
    category: 'Inspection',
    keywords: ['dirname', 'path', 'directory'],
  },
  {
    cmd: 'realpath',
    short: 'Print the resolved absolute path',
    long: 'Resolves any `.`, `..`, or relative segments and prints a clean absolute path.',
    examples: ['realpath ../notes.txt', 'realpath ~/projects'],
    category: 'Inspection',
    keywords: ['realpath', 'absolute', 'path', 'resolve'],
  },
  {
    cmd: 'diff',
    short: 'Compare two files line by line',
    long: 'Walks both files and prints lines that differ, prefixed with `<` (first file) or `>` (second file). When files match, prints `(files are identical)`.',
    examples: ['diff old.txt new.txt'],
    category: 'Inspection',
    keywords: ['diff', 'compare', 'difference', 'patch'],
  },
  {
    cmd: 'tail',
    short: 'Show the last lines of a file',
    long: 'By default prints the last 10 lines. Pass `-n N` to change the count. Combine with `-f` (simulated) to follow a growing log file.',
    examples: ['tail notes.txt', 'tail -n 5 /var/log/syslog'],
    category: 'Inspection',
    keywords: ['end', 'last', 'lines', 'log', 'follow'],
  },
  {
    cmd: 'grep',
    short: 'Search text for a pattern (supports -i -v -n)',
    long: 'Prints lines that match a pattern. `-i` ignores case, `-v` inverts the match, `-n` prefixes each hit with its line number. Combine with `|` to filter any command’s output.',
    examples: ['grep error app.log', 'grep -in "TODO" notes.txt', 'cat app.log | grep 500'],
    category: 'Search',
    keywords: ['grep', 'search', 'pattern', 'regex', 'match', 'filter'],
  },
  {
    cmd: 'sort',
    short: 'Sort lines of text (supports -r -n -u)',
    long: 'Orders lines alphabetically by default. `-n` sorts numerically, `-r` reverses, `-u` keeps only unique lines.',
    examples: ['sort names.txt', 'sort -nr scores.txt', 'sort -u tags.txt'],
    category: 'Text',
    keywords: ['sort', 'order', 'alphabetical', 'numeric', 'unique'],
  },
  {
    cmd: 'uniq',
    short: 'Remove adjacent duplicate lines (supports -c -i)',
    long: 'Collapses runs of identical adjacent lines into one. For a global unique pass, pipe through `sort` first: `sort file | uniq`. `-c` prefixes each line with a count.',
    examples: ['uniq -c access.log', 'sort tags.txt | uniq'],
    category: 'Text',
    keywords: ['uniq', 'unique', 'duplicate', 'dedupe'],
  },
  {
    cmd: 'cut',
    short: 'Cut fields or characters from input',
    long: 'Splits each line by a delimiter (`-d`, default Tab) and prints the chosen fields (`-f`) or character positions (`-c`). Lists like `1,3-5` are supported.',
    examples: ['cut -d: -f1 /etc/passwd', 'cut -c1-10 file.txt'],
    category: 'Text',
    keywords: ['cut', 'field', 'column', 'delimiter', 'csv'],
  },
  {
    cmd: 'tr',
    short: 'Translate or delete characters',
    long: 'Maps characters in SET1 to characters in SET2 (one-to-one, by position). `-d` deletes the listed characters instead. Reads from a file argument or piped stdin.',
    examples: ['tr a-z A-Z < file.txt', 'tr -d "\\r" < dos.txt'],
    category: 'Text',
    keywords: ['tr', 'translate', 'delete', 'lowercase', 'uppercase'],
  },
  {
    cmd: 'tac',
    short: 'Print lines in reverse order',
    long: 'Reads a file and prints its lines from bottom to top. `cat` reversed, character-by-character.',
    examples: ['tac notes.txt'],
    category: 'Text',
    keywords: ['tac', 'reverse', 'lines'],
  },
  {
    cmd: 'rev',
    short: 'Reverse each line of input',
    long: 'Reads input and prints each line with its characters in reverse order. Lines themselves stay in order.',
    examples: ['rev names.txt'],
    category: 'Text',
    keywords: ['rev', 'reverse', 'characters', 'mirror'],
  },
  {
    cmd: 'nl',
    short: 'Number lines of input',
    long: 'Prefixes each non-empty line with its 1-based line number, right-aligned in 6 columns. Pair with `cat` to get a numbered listing.',
    examples: ['nl notes.txt', 'cat notes.txt | nl'],
    category: 'Text',
    keywords: ['nl', 'number', 'lines', 'enumerate'],
  },
  {
    cmd: 'paste',
    short: 'Merge lines of files side by side (-d delim)',
    long: 'Reads two or more files in parallel and joins their lines column-by-column with a delimiter (default Tab).',
    examples: ['paste names.txt phones.txt', 'paste -d, a.csv b.csv'],
    category: 'Text',
    keywords: ['paste', 'merge', 'columns', 'csv'],
  },
  {
    cmd: 'join',
    short: 'Join two files on a common field',
    long: 'Merges two files by matching the first whitespace-separated field of each line. Both files must be sorted on that field.',
    examples: ['join users.txt groups.txt'],
    category: 'Text',
    keywords: ['join', 'merge', 'sql', 'relational'],
  },
  {
    cmd: 'md5sum',
    short: 'Print MD5-style digests of files',
    long: 'Hashes each file and prints a 32-hex digest followed by the filename. Use it to spot-check that a file has not changed. (Sandbox: non-cryptographic.)',
    examples: ['md5sum *.iso'],
    category: 'Inspection',
    keywords: ['md5', 'hash', 'checksum', 'digest', 'verify'],
  },
  {
    cmd: 'sha256sum',
    short: 'Print SHA-256-style digests of files',
    long: 'Hashes each file and prints a 64-hex digest followed by the filename. Stronger than MD5 for tamper detection. (Sandbox: non-cryptographic.)',
    examples: ['sha256sum backup.tar'],
    category: 'Inspection',
    keywords: ['sha256', 'hash', 'checksum', 'digest', 'verify'],
  },
  {
    cmd: 'strings',
    short: 'Print printable strings (≥4 chars) from a file',
    long: 'Pulls out runs of printable ASCII at least 4 characters long. Classic tool for inspecting binary blobs.',
    examples: ['strings app.bin | less'],
    category: 'Inspection',
    keywords: ['strings', 'binary', 'ascii', 'extract'],
  },
  {
    cmd: 'od',
    short: 'Dump file in octal / hex / chars',
    long: 'Prints a numbered byte dump of the file. `-x` shows hex, `-c` shows printable characters (escapes for control bytes), default is octal.',
    examples: ['od -c notes.txt', 'od -x notes.txt'],
    category: 'Inspection',
    keywords: ['od', 'octal', 'hex', 'dump', 'bytes'],
  },
  {
    cmd: 'sed',
    short: 'Stream editor — supports s/find/replace/[g]',
    long: 'Applies a substitution expression to one or more files. The sandbox only supports the `s/find/replace/g` form (no addresses, no other commands). Add `g` to replace every match on a line.',
    examples: ['sed "s/old/new/g" notes.txt', "sed 's/foo/bar/' file.txt"],
    category: 'Text',
    keywords: ['sed', 'substitute', 'replace', 'stream', 'editor'],
  },
  {
    cmd: 'awk',
    short: 'Simple awk — `awk "{print $N}"` prints field N',
    long: 'The sandbox accepts the most common form: `awk "{print $N}" file` prints whitespace-separated field N of every line. `$0` prints the whole line.',
    examples: ['awk "{print $1}" access.log', 'awk "{print $0}" notes.txt'],
    category: 'Text',
    keywords: ['awk', 'field', 'column', 'gawk'],
  },
  {
    cmd: 'xxd',
    short: 'Hex dump of a file',
    long: 'Prints a hex+ASCII view of the file, 16 bytes per line. Useful for inspecting binary data and reverse engineering.',
    examples: ['xxd app.bin | head'],
    category: 'Inspection',
    keywords: ['xxd', 'hex', 'dump', 'binary'],
  },
  {
    cmd: 'base64',
    short: 'base64 encode or decode',
    long: 'Reads a file and either base64-encodes it (default) or decodes it (`-d`). Handy for embedding binary in JSON or copying certs as text.',
    examples: ['base64 photo.png', 'base64 -d ciphertext.txt'],
    category: 'Text',
    keywords: ['base64', 'encode', 'decode', 'binary'],
  },
  {
    cmd: 'tee',
    short: 'Read stdin, write to file and stdout (-a appends)',
    long: 'Splits a pipeline: the data flows through to stdout and is also written to one or more files. `-a` appends instead of overwriting.',
    examples: ['echo hello | tee out.txt', 'cat log | tee -a all.log | grep ERROR'],
    category: 'Text',
    keywords: ['tee', 'pipe', 'split', 'tee off'],
  },
  {
    cmd: 'xargs',
    short: 'Build and execute command lines (simulated)',
    long: 'Takes whitespace-separated tokens from stdin and runs the given command once per token, appending the token as the last argument. Lets you turn `find` output into a batch job.',
    examples: ['find . -name "*.log" | xargs rm', 'echo "a b c" | xargs echo item:'],
    category: 'Text',
    keywords: ['xargs', 'batch', 'pipe', 'arguments'],
  },
  {
    cmd: 'printf',
    short: 'Format and print data',
    long: 'Like `echo` but with C-style format specifiers. `%s` inserts the next argument as a string, `%d` parses the next argument as an integer. Useful in scripts where you need exact control.',
    examples: ['printf "hello %s\\n" world', 'printf "%d + %d = %d\\n" 1 2 3'],
    category: 'Editing',
    keywords: ['printf', 'format', 'template', 'string'],
  },
  {
    cmd: 'yes',
    short: 'Print a string repeatedly',
    long: 'Echoes its argument (or `y`) on repeat, forever in a real shell. The sandbox prints five lines and a `... (truncated)` marker so it does not flood the terminal.',
    examples: ['yes', 'yes "I agree" | head -n 3'],
    category: 'Editing',
    keywords: ['yes', 'repeat', 'confirm'],
  },
  {
    cmd: 'history',
    short: 'Show recent commands',
    long: 'Prints the in-memory history of commands you have run in the current sandbox session, numbered so you can refer to them.',
    examples: ['history', 'history | tail -n 5'],
    category: 'Help',
    keywords: ['history', 'recall', 'previous', 'replay'],
  },
  {
    cmd: 'env',
    short: 'Print environment variables',
    long: 'Lists all variables currently set in the shell’s environment, one per line as `NAME=value`. Use `export NAME=value` to set one.',
    examples: ['env', 'env | grep PATH'],
    category: 'System',
    keywords: ['env', 'environment', 'variables', 'export'],
  },
  {
    cmd: 'export',
    short: 'Set an environment variable',
    long: 'Adds (or updates) a variable in the shell’s environment. Format is `export NAME=value`. Variables set this way are visible to subsequent commands in the same session.',
    examples: ['export EDITOR=vim', 'export PATH="$HOME/bin:$PATH"'],
    category: 'System',
    keywords: ['export', 'set', 'variable', 'environment'],
  },
  {
    cmd: 'exit',
    short: 'Exit the shell (simulated)',
    long: 'Acknowledges the request and prints `logout`. The in-browser shell cannot really be closed — refresh the page to start a new session.',
    examples: ['exit'],
    category: 'System',
    keywords: ['exit', 'quit', 'logout', 'bye'],
  },
  {
    cmd: 'sleep',
    short: 'Pause for N seconds (simulated)',
    long: 'Real `sleep` waits in real time. The sandbox returns immediately so your lesson does not stall.',
    examples: ['sleep 1', 'sleep 0.5 && echo done'],
    category: 'System',
    keywords: ['sleep', 'wait', 'pause', 'delay'],
  },
  {
    cmd: 'true',
    short: 'Do nothing, successfully',
    long: 'Exits with status 0 and produces no output. Mostly useful in shell scripts: `while true; do ...; done`.',
    examples: ['true'],
    category: 'System',
    keywords: ['true', 'yes', 'success', 'noop'],
  },
  {
    cmd: 'false',
    short: 'Do nothing, unsuccessfully',
    long: 'Exits with a non-zero status and produces no output. Useful for testing `&&` / `||` chains.',
    examples: ['false || echo "fell through"'],
    category: 'System',
    keywords: ['false', 'no', 'failure', 'noop'],
  },
  {
    cmd: 'arch',
    short: 'Print machine architecture',
    long: 'Always reports `x86_64` in the sandbox. In real Linux it returns the CPU architecture of the host.',
    examples: ['arch'],
    category: 'System',
    keywords: ['arch', 'architecture', 'cpu', 'x86_64'],
  },
  {
    cmd: 'nproc',
    short: 'Print the number of processing units available',
    long: 'Returns the number of logical CPU cores. The sandbox reports 4. Used in build scripts to parallelise jobs.',
    examples: ['nproc', 'make -j$(nproc)'],
    category: 'System',
    keywords: ['nproc', 'cpu', 'cores', 'parallel'],
  },
  {
    cmd: 'lsblk',
    short: 'List block devices',
    long: 'Prints a tree of disks and partitions: names, sizes, mountpoints. Sandbox returns a small fixed example so you can recognise the columns.',
    examples: ['lsblk', 'lsblk -f'],
    category: 'System',
    keywords: ['lsblk', 'disk', 'partition', 'block', 'mount'],
  },
  {
    cmd: 'lscpu',
    short: 'Display CPU architecture information',
    long: 'Detailed dump of CPU model, cores, threads, cache sizes and feature flags. Sandbox returns a representative sample.',
    examples: ['lscpu'],
    category: 'System',
    keywords: ['lscpu', 'cpu', 'cache', 'flags'],
  },
  {
    cmd: 'lsmem',
    short: 'List the ranges of available memory',
    long: 'Summarises the physical memory ranges the kernel can see, with size and online/offline state. Sandbox returns a small sample.',
    examples: ['lsmem'],
    category: 'System',
    keywords: ['lsmem', 'memory', 'ram', 'numa'],
  },
  {
    cmd: 'lsof',
    short: 'List open files (simulated)',
    long: 'Classic sysadmin tool. In a real shell it lists every open file descriptor. The sandbox returns a few example entries so the columns make sense.',
    examples: ['lsof', 'lsof /etc/passwd'],
    category: 'System',
    keywords: ['lsof', 'open', 'files', 'fd', 'descriptor'],
  },
  {
    cmd: 'dmesg',
    short: 'Print the kernel ring buffer (simulated)',
    long: 'Shows the kernel’s recent log messages — useful for spotting hardware or driver problems at boot. Sandbox returns a representative slice.',
    examples: ['dmesg', 'dmesg | grep -i usb'],
    category: 'System',
    keywords: ['dmesg', 'kernel', 'log', 'boot'],
  },
  {
    cmd: 'last',
    short: 'Show last logged-in users (simulated)',
    long: 'Reads `/var/log/wtmp` (sandbox: a small static sample) and prints the recent login history, with session durations.',
    examples: ['last', 'last learner'],
    category: 'System',
    keywords: ['last', 'login', 'history', 'wtmp'],
  },
  {
    cmd: 'who',
    short: 'Show who is logged on',
    long: 'Prints one line per currently logged-in user: username, terminal, login time, and remote host (in parentheses).',
    examples: ['who', 'who -b'],
    category: 'System',
    keywords: ['who', 'logged in', 'users', 'sessions'],
  },
  {
    cmd: 'groups',
    short: 'Print group memberships for a user',
    long: 'With no argument, lists the groups of the current user. With a username, lists that user’s groups.',
    examples: ['groups', 'groups root'],
    category: 'Permissions',
    keywords: ['groups', 'membership', 'user', 'gid'],
  },
  {
    cmd: 'logname',
    short: "Return the user's login name",
    long: 'Prints the account name that was used to log into the current session, even after a `su` switch.',
    examples: ['logname'],
    category: 'System',
    keywords: ['logname', 'login', 'user', 'identity'],
  },
  {
    cmd: 'vmstat',
    short: 'Report virtual memory statistics',
    long: 'A one-line snapshot of process, memory, swap, I/O and CPU activity. Sandbox returns a representative line.',
    examples: ['vmstat', 'vmstat 2'],
    category: 'System',
    keywords: ['vmstat', 'memory', 'swap', 'cpu', 'stats'],
  },
  {
    cmd: 'iostat',
    short: 'Report CPU and I/O statistics',
    long: 'Per-device and CPU utilisation numbers — useful for spotting I/O bottlenecks. Sandbox returns a representative table.',
    examples: ['iostat', 'iostat -xz 2'],
    category: 'System',
    keywords: ['iostat', 'io', 'cpu', 'disk', 'stats'],
  },
  {
    cmd: 'history_stats',
    short: 'Show most-used commands from this session',
    long: 'Tallies how many times each command appears in the current session’s history and ranks them. Great for spotting your habits.',
    examples: ['history_stats'],
    category: 'Help',
    keywords: ['history', 'stats', 'most used', 'frequent'],
  },
  {
    cmd: 'kill',
    short: 'Send a signal to a process (simulated)',
    long: 'Takes a process ID and (in real shells) sends a signal — default `TERM`. Sandbox acknowledges the request and refuses non-numeric PIDs.',
    examples: ['kill 1234', 'kill -9 1234'],
    category: 'System',
    keywords: ['kill', 'signal', 'pid', 'terminate'],
  },
  {
    cmd: 'id',
    short: 'Print user identity',
    long: 'Prints the numeric UID, primary GID and the full list of group memberships for the current user.',
    examples: ['id', 'id root'],
    category: 'Permissions',
    keywords: ['id', 'uid', 'gid', 'identity'],
  },
  {
    cmd: 'which',
    short: 'Locate a command',
    long: 'Prints the absolute path of the executable that would run if you typed the command. In the sandbox it returns `/usr/bin/<cmd>` for known commands.',
    examples: ['which ls', 'which python'],
    category: 'System',
    keywords: ['which', 'locate', 'path', 'executable'],
  },
  {
    cmd: 'man',
    short: 'Show short help for a command',
    long: 'Like `help` but for one command at a time. Prints a small man-page-style summary (NAME, SYNOPSIS, DESCRIPTION).',
    examples: ['man ls', 'man grep'],
    category: 'Help',
    keywords: ['man', 'manual', 'help', 'docs'],
  },
  {
    cmd: 'sudo',
    short: 'Run a command as another user (simulated)',
    long: 'Pretends to elevate privileges and runs the command. The sandbox cannot really escalate, but the call is accepted so scripts keep working.',
    examples: ['sudo apt update', 'sudo systemctl restart nginx'],
    category: 'Permissions',
    keywords: ['sudo', 'root', 'privilege', 'admin'],
  },
  {
    cmd: 'nohup',
    short: 'Run a command immune to hangups (simulated)',
    long: 'In real Linux, `nohup` lets a command keep running after you log out. The sandbox acknowledges the request but does not background processes.',
    examples: ['nohup ./long-job.sh &'],
    category: 'System',
    keywords: ['nohup', 'background', 'hangup', 'detach'],
  },
  {
    cmd: 'ifconfig',
    short: 'Show network interfaces',
    long: 'Older but still-common tool for inspecting IP addresses, MAC addresses and packet counts per interface. (`ip addr` is the modern equivalent.)',
    examples: ['ifconfig', 'ifconfig eth0'],
    category: 'Network',
    keywords: ['ifconfig', 'network', 'interface', 'ip', 'mac'],
  },
  {
    cmd: 'ip',
    short: 'Show / manipulate routing (simulated, `ip addr`)',
    long: 'Modern replacement for `ifconfig`. The sandbox only supports `ip addr`, which prints the active IPv4 and IPv6 addresses per interface.',
    examples: ['ip addr', 'ip a'],
    category: 'Network',
    keywords: ['ip', 'addr', 'address', 'route', 'network'],
  },
  {
    cmd: 'ping',
    short: 'Ping a host (simulated)',
    long: 'Sends ICMP echo requests to a host and reports round-trip times. The sandbox simulates a successful three-packet exchange.',
    examples: ['ping learninx.dev', 'ping -c 3 1.1.1.1'],
    category: 'Network',
    keywords: ['ping', 'icmp', 'network', 'latency'],
  },
  {
    cmd: 'curl',
    short: 'Fetch a URL (simulated)',
    long: 'Pretends to make an HTTP request. `-I` / `--head` returns just the response headers; without it, returns a small HTML stub.',
    examples: ['curl https://learninx.dev', 'curl -I https://learninx.dev'],
    category: 'Network',
    keywords: ['curl', 'http', 'fetch', 'download', 'api'],
  },
  {
    cmd: 'wget',
    short: 'Download a URL to disk (simulated)',
    long: 'Like `curl`, but writes the response to a file by default. Sandbox reports a successful download with byte count.',
    examples: ['wget https://learninx.dev/index.html'],
    category: 'Network',
    keywords: ['wget', 'download', 'http', 'mirror'],
  },
  {
    cmd: 'ssh',
    short: 'Open a remote shell (simulated)',
    long: 'Pretends to log into the given host (format `user@host`) and prints a sample welcome banner.',
    examples: ['ssh learner@learninx.dev', 'ssh root@server.local'],
    category: 'Network',
    keywords: ['ssh', 'remote', 'login', 'shell'],
  },
  {
    cmd: 'chmod',
    short: 'Change file permissions',
    long: 'Updates the read / write / execute bits. The octal form is easiest: 7 = rwx, 6 = rw-, 5 = r-x, 4 = r--, 0 = ---. In the sandbox the change is acknowledged but not enforced.',
    examples: ['chmod +x script.sh', 'chmod 755 script.sh', 'chmod 600 secret.txt'],
    category: 'Permissions',
    keywords: ['permissions', 'mode', 'rwx', 'octal', 'executable'],
  },
  {
    cmd: 'ps',
    short: 'List running processes',
    long: 'Without flags, lists processes in the current session. `ps aux` (supported in the sandbox) gives the full system-wide view with CPU and memory columns.',
    examples: ['ps', 'ps aux'],
    category: 'System',
    keywords: ['processes', 'list', 'running', 'pid', 'ps'],
  },
  {
    cmd: 'top',
    short: 'Live process viewer (snapshot)',
    long: 'In a real terminal `top` updates continuously. The sandbox prints a single representative frame so you can read the columns without a live REPL.',
    examples: ['top', 'top -n 1'],
    category: 'System',
    keywords: ['top', 'processes', 'monitor', 'tasks', 'cpu'],
  },
  {
    cmd: 'chain',
    short: 'Chain commands with ;, &&, ||, and pipe with |',
    long: 'The Learninx shell supports the four classic control operators. `;` runs unconditionally. `&&` runs the right side only if the left side succeeded. `||` runs only on failure. `|` passes the left side’s stdout into the right side’s stdin.',
    examples: [
      'ls && echo done',
      'cat file | grep error',
      'false || echo "fell through"',
      'echo a ; echo b',
    ],
    category: 'Help',
    keywords: ['chain', 'and', 'or', 'pipe', 'semicolon', '&&', '||', '|'],
  },
  {
    cmd: 'uname',
    short: 'Print system information',
    long: 'Prints the kernel name. `-a` includes the version, architecture and hostname.',
    examples: ['uname', 'uname -a'],
    category: 'System',
    keywords: ['system', 'kernel', 'info', 'version'],
  },

  // Inspection
  {
    cmd: 'cat',
    short: 'Print the contents of a file',
    long: 'Writes the file to standard output. Great for short files. For longer files prefer `less` or `head` / `tail`.',
    examples: ['cat notes.txt', 'cat /etc/hostname'],
    category: 'Inspection',
    keywords: ['print', 'read', 'file', 'contents', 'show'],
  },
  {
    cmd: 'head',
    short: 'Show the first lines of a file',
    long: 'By default prints the first 10 lines. Pass `-n` to change the count.',
    examples: ['head notes.txt', 'head -n 5 /etc/passwd'],
    category: 'Inspection',
    keywords: ['start', 'first', 'lines', 'file'],
  },
  {
    cmd: 'wc',
    short: 'Count lines, words and bytes',
    long: 'By default prints three numbers: lines, words, bytes. Common flags: `-l` (lines only), `-w` (words only), `-c` (bytes only).',
    examples: ['wc notes.txt', 'wc -l notes.txt'],
    category: 'Inspection',
    keywords: ['count', 'lines', 'words', 'bytes'],
  },

  // Editing
  {
    cmd: 'echo',
    short: 'Print text to the screen',
    long: 'Writes its arguments to standard output. Combine with `>` to write to a file or `>>` to append.',
    examples: ['echo hello', 'echo hello > notes.txt', 'echo more >> notes.txt'],
    category: 'Editing',
    keywords: ['print', 'text', 'write', 'redirect'],
  },
  {
    cmd: 'nano',
    short: 'Beginner-friendly text editor',
    long: 'In the sandbox, `nano file` prints a TUI-style view of the file and tells you which commands to use for real edits. Use `echo > file` to overwrite or `>>` to append.',
    examples: ['nano notes.txt'],
    category: 'Editing',
    keywords: ['editor', 'simple', 'text', 'beginner'],
  },
  {
    cmd: 'vi / vim',
    short: 'Modal text editor',
    long: 'In the sandbox this prints a TUI view and lists the editing commands. In a real terminal: press `i` to enter insert mode, `Esc` to leave, `:wq` to save and quit.',
    examples: ['vi notes.txt', 'vim notes.txt'],
    category: 'Editing',
    keywords: ['editor', 'vim', 'vi', 'modal', 'advanced'],
  },

  // Permissions
  {
    cmd: 'chmod',
    short: 'Change file permissions',
    long: 'Updates the read / write / execute bits. The octal form is easiest: 7 = rwx, 6 = rw-, 5 = r-x, 4 = r--, 0 = ---.',
    examples: ['chmod +x script.sh', 'chmod 755 script.sh', 'chmod 600 secret.txt'],
    category: 'Permissions',
    keywords: ['permissions', 'mode', 'rwx', 'octal'],
  },
  {
    cmd: 'ps',
    short: 'List running processes',
    long: 'Shows the processes started in the current sandbox shell. Informational only — you cannot kill other sessions.',
    examples: ['ps'],
    category: 'Permissions',
    keywords: ['processes', 'list', 'running'],
  },

  // System
  {
    cmd: 'uname',
    short: 'Print system information',
    long: 'Prints the kernel name. `-a` includes the version, architecture and hostname.',
    examples: ['uname', 'uname -a'],
    category: 'System',
    keywords: ['system', 'kernel', 'info', 'version'],
  },
  {
    cmd: 'uptime',
    short: 'Show how long the system has been up',
    long: 'Prints a short uptime line. In the sandbox this is a simulated value.',
    examples: ['uptime'],
    category: 'System',
    keywords: ['uptime', 'load', 'time'],
  },
  {
    cmd: 'free',
    short: 'Show memory usage',
    long: 'Prints total, used and free memory. `-h` switches to human-readable units (K, M, G).',
    examples: ['free', 'free -h'],
    category: 'System',
    keywords: ['memory', 'ram', 'usage'],
  },
  {
    cmd: 'df',
    short: 'Show disk space usage',
    long: 'Reports the filesystem disk space usage. `-h` switches to human-readable units.',
    examples: ['df', 'df -h'],
    category: 'System',
    keywords: ['disk', 'space', 'storage', 'filesystem'],
  },
  {
    cmd: 'whoami',
    short: 'Print the current user',
    long: 'Writes your current username. In the sandbox you are always `learner`.',
    examples: ['whoami'],
    category: 'System',
    keywords: ['user', 'current', 'identity'],
  },
  {
    cmd: 'hostname',
    short: 'Print the system hostname',
    long: 'Writes the name of the current machine.',
    examples: ['hostname'],
    category: 'System',
    keywords: ['host', 'machine', 'name'],
  },
  {
    cmd: 'date',
    short: 'Show the current date and time',
    long: 'Prints the current local date and time.',
    examples: ['date'],
    category: 'System',
    keywords: ['date', 'time', 'clock'],
  },
  {
    cmd: 'clear',
    short: 'Clear the terminal',
    long: 'Scrolls the terminal so the prompt sits at the top of the visible area. Shortcut: Ctrl+L.',
    examples: ['clear'],
    category: 'System',
    keywords: ['clear', 'reset', 'screen'],
  },
  {
    cmd: 'help',
    short: 'List available commands',
    long: 'Prints the full list of sandbox commands with one-line descriptions.',
    examples: ['help'],
    category: 'Help',
    keywords: ['help', 'list', 'commands'],
  },
  {
    cmd: 'top',
    short: 'Show running processes (read-only)',
    long: 'In the sandbox this prints a static snapshot of process activity. The full interactive `top` is not available in the in-browser shell.',
    examples: ['top'],
    category: 'Help',
    keywords: ['top', 'processes', 'monitor', 'tasks'],
  },
];

export const CHEAT_CATEGORIES: CheatCategory[] = [
  'Navigation',
  'Files',
  'Inspection',
  'Editing',
  'Text',
  'Search',
  'Permissions',
  'Network',
  'Archiving',
  'System',
  'Help',
];

export function cheatMatches(entry: CheatEntry, q: string): boolean {
  if (!q) return true;
  const needle = q.toLowerCase();
  const haystack = [
    entry.cmd,
    entry.short,
    entry.long,
    entry.category,
    ...entry.examples,
    ...entry.keywords,
  ]
    .join(' ')
    .toLowerCase();
  return haystack.includes(needle);
}
